### 전국 신용카드 승인금액

In [1]:
import pandas as pd

# csv파일 불러오기
df = pd.read_csv('./data/카드_전국.csv')
df.head()

,날짜,전국_합계,전국_종합소매,전국_ 백화점,전국_ 대형마트/유통전문점,전국_ 슈퍼마켓,전국_ 편의점,전국_ 면세점,전국_전자상거래/통신판매,전국_식료품,...,전국_오락/문화,전국_ 스포츠/오락/여가,전국_ 서적/문구,전국_교육,전국_숙박/음식,전국_ 숙박,전국_ 음식점,전국_공과금/개인 및 전문 서비스,전국_금융/보험,전국_기타
0,2012/11,299970.34,53558.49,13695.10,26123.23,10604.38,1826.54,1309.25,29166.45,4778.33,...,13142.50,10450.19,2692.31,8644.69,33317.61,2119.99,31197.62,25205.61,10618.86,18468.27
1,2012/12,310533.02,57731.17,14542.45,28802.59,11308.05,1810.70,1267.38,29971.83,4895.34,...,12041.55,9030.65,3010.90,8440.60,37410.08,2454.51,34955.56,25947.67,10529.91,19655.81
2,2013/01,296732.27,51384.80,11189.07,25640.42,11435.88,1778.78,1340.65,28545.80,5024.76,...,10803.91,8001.41,2802.50,8776.78,34309.86,2458.03,31851.83,30498.42,10421.99,19792.28
3,2013/02,267365.92,48141.86,9748.40,25035.42,10602.32,1652.60,1103.11,24596.71,5510.28,...,9302.49,6800.21,2502.28,8431.41,28779.93,1821.75,26958.18,25149.57,9509.00,18103.45
4,2013/03,295640.18,49572.79,10873.94,24769.86,10904.74,1877.38,1146.88,26704.28,4775.35,...,12895.59,9214.35,3681.25,8996.41,34196.47,1898.21,32298.26,25570.21,10253.94,19820.98

In [2]:
# 날짜 컬럼 "/" 제거
df["날짜"] = df["날짜"].str.replace("/", "")

# 날짜 컬럼 int 타입으로 변환
df["날짜"] = df["날짜"].astype(int)

# 날짜 데이터타임 변환 후 인덱스 변환
df["날짜"] = pd.to_datetime(df["날짜"], format='%Y%m')
df["날짜"] = df["날짜"].dt.strftime('%Y-%m')
df.set_index('날짜', inplace=True)

In [3]:
# 컬럼 맞추기
df.columns = df.columns.str.replace('_ ','_')
df.columns = df.columns.str.replace(' ','')
df.columns

Index(['전국_합계', '전국_종합소매', '전국_백화점', '전국_대형마트/유통전문점', '전국_슈퍼마켓', '전국_편의점',
       '전국_면세점', '전국_전자상거래/통신판매', '전국_식료품', '전국_일반식료품', '전국_건강보조식품',
       '전국_의류/잡화', '전국_의복/직물', '전국_복식잡화', '전국_시계/귀금속/안경', '전국_화장품', '전국_연료',
       '전국_가구/가전', '전국_가구', '전국_가전제품/정보통신기기', '전국_의료/보건', '전국_종합병원',
       '전국_일반병의원/기타의료기관', '전국_자동차', '전국_국산자동차신품', '전국_기타운송수단', '전국_자동차부품및정비',
       '전국_여행/교통', '전국_여행사/자동차임대', '전국_항공사', '전국_대중교통', '전국_오락/문화',
       '전국_스포츠/오락/여가', '전국_서적/문구', '전국_교육', '전국_숙박/음식', '전국_숙박', '전국_음식점',
       '전국_공과금/개인및전문서비스', '전국_금융/보험', '전국_기타'],
      dtype='object')

In [4]:
df.columns = ['합계', '종합소매', '백화점', '대형마트/유통전문점', '슈퍼마켓', '편의점',
       '면세점', '전자상거래/통신판매', '식료품', '일반식료품', '건강보조식품',
       '의류/잡화', '의복/직물', '복식잡화', '시계/귀금속/안경', '화장품', '연료',
       '가구/가전', '가구', '가전제품/정보통신기기', '의료/보건', '종합병원',
       '일반병의원/기타의료기관', '자동차', '국산자동차신품', '기타운송수단', '자동차부품및정비',
       '여행/교통', '여행사/자동차임대', '항공사', '대중교통', '오락/문화',
       '스포츠/오락/여가', '서적/문구', '교육', '숙박/음식', '숙박', '음식점',
       '공과금/개인및전문서비스', '금융/보험', '기타']

### 분류별 상품 나누기

In [5]:
# 합계 분류 하기
df_t = df[['종합소매','전자상거래/통신판매', '식료품','의류/잡화', 
'연료','가구/가전', '의료/보건', '자동차', '여행/교통', '스포츠/오락/여가', '서적/문구', '교육','숙박','음식점'
,'공과금/개인및전문서비스', '금융/보험']]
# 등락률 구하기
df_t1 = df[['종합소매','전자상거래/통신판매', '식료품','의류/잡화',
'연료','가구/가전', '의료/보건', '자동차', '여행/교통', '스포츠/오락/여가', '서적/문구', '교육','숙박','음식점'
,'공과금/개인및전문서비스', '금융/보험']].pct_change().round(2)

### 소비자 물가지수 불러오기

In [6]:
cpi_df = pd.read_csv('./csv/소비자물가지수_2020100__20220811151333.csv',encoding='cp949')

# 컬럼 문자열로 바꾸기
cpi_df["시점"] = cpi_df["시점"].astype(str)

# .10 이 .1로 변환된 걸 다시 재변환
cpi_df["시점"][cpi_df["시점"].str.endswith(".1")] = cpi_df["시점"][cpi_df["시점"].str.endswith(".1")]+"0"

# 컬럼명 변경
cpi_df.rename(columns={'전국' : '소비자물가지수'}, inplace=True)
# 날짜 맞추기
cpi_df = cpi_df.iloc[:-3]

# 데이터타임 변황 후 시점컬럼명 날짜로 바꾸기
cpi_df["시점"] = pd.to_datetime(cpi_df["시점"], format="%Y.%m")
cpi_df["시점"] = cpi_df["시점"].dt.strftime('%Y-%m')
cpi_df.rename(columns={"시점" : "날짜"}, inplace=True)
cpi_df.set_index('날짜', inplace=True)
cpi_df

C:\Users\82104\AppData\Local\Temp\ipykernel_24612\3132659229.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cpi_df["시점"][cpi_df["시점"].str.endswith(".1")] = cpi_df["시점"][cpi_df["시점"].str.endswith(".1")]+"0"
C:\Users\82104\AppData\Local\Temp\ipykernel_24612\3132659229.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cpi_df["시점"] = pd.to_datetime(cpi_df["시점"], format="%Y.%m")
C:\Users\82104\AppData\Local\Temp\ipykernel_24612\3132659229.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cpi_df["시점"] = cpi_df["시점"].dt.strftime('%Y-%m')
C:\Users\82104\AppData\Local\Temp\ipykernel_24612\3132659229.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cpi_df.rename(columns={"시점" : "날짜"}, inplace=True)

         소비자물가지수
날짜
2012-11   92.011
2012-12   92.175
2013-01   92.728
2013-02   93.038
2013-03   92.952
...          ...
2021-12  104.040
2022-01  104.690
2022-02  105.300
2022-03  106.060
2022-04  106.850

[114 rows x 1 columns]

### 시장금리 불러오기

In [7]:
interest_rates_df = pd.read_csv('./csv/시장금리.csv')
interest_rates_df.set_index('날짜', inplace=True)
interest_rates_df

,국고채_3년_평균,국고채_5년_평균,국고채_10년_평균,회사채_3년_평균,CD_91몰_평균,콜금리_1일몰_평균,기준금리
날짜,,,,,,,
2012-11,2.80,2.87,2.99,3.32,2.85,2.75,2.75
2012-12,2.85,2.98,3.13,3.30,2.88,2.75,2.75
2013-01,2.75,2.86,3.05,3.20,2.86,2.76,2.75
2013-02,2.70,2.83,3.04,3.06,2.83,2.75,2.75
2013-03,2.60,2.69,2.91,2.95,2.81,2.74,2.75
...,...,...,...,...,...,...,...
2021-12,1.80,1.98,2.19,2.41,1.27,1.01,1.00
2022-01,2.06,2.28,2.49,2.63,1.39,1.19,1.25
2022-02,2.29,2.50,2.69,2.87,1.50,1.22,1.25
2022-03,2.37,2.60,2.78,3.03,1.50,1.24,1.25
2022-04,2.94,3.14,3.22,3.63,1.64,1.30,1.50

### 소매판매지수 불러오기

In [8]:
socell_df = pd.read_csv('./csv/소매판매지수_1211_2204.csv')
socell_df = socell_df[['날짜','불변_총지수']]
socell_df.rename(columns={'불변_총지수' : '소매판매지수'}, inplace=True)
socell_df.set_index('날짜', inplace=True)
socell_df

         소매판매지수
날짜
2012-11    97.5
2012-12    99.8
2013-01    91.2
2013-02    86.8
2013-03    93.6
...         ...
2021-12   127.2
2022-01   117.5
2022-02   107.9
2022-03   122.0
2022-04   119.4

[114 rows x 1 columns]

### 카드 소비 합치기

In [9]:
total_csi = pd.merge(cpi_df, socell_df, how='left', left_index=True, right_index=True)
total_csi = pd.merge(total_csi, interest_rates_df,  how='left', left_index=True, right_index=True)
total_csi.drop_duplicates(inplace=True)
total_csi.head()

,소비자물가지수,소매판매지수,국고채_3년_평균,국고채_5년_평균,국고채_10년_평균,회사채_3년_평균,CD_91몰_평균,콜금리_1일몰_평균,기준금리
날짜,,,,,,,,,
2012-11,92.011,97.5,2.80,2.87,2.99,3.32,2.85,2.75,2.75
2012-12,92.175,99.8,2.85,2.98,3.13,3.30,2.88,2.75,2.75
2013-01,92.728,91.2,2.75,2.86,3.05,3.20,2.86,2.76,2.75
2013-02,93.038,86.8,2.70,2.83,3.04,3.06,2.83,2.75,2.75
2013-03,92.952,93.6,2.60,2.69,2.91,2.95,2.81,2.74,2.75

### 코로나 전 후 비교를 위한 기간설정

In [173]:
df_t = df_t.iloc[:86]
cpi_df = cpi_df.iloc[:-28]
interest_rates_df = interest_rates_df.iloc[:-28]
socell_df = socell_df.iloc[:-28]

### 상관관계

In [12]:
# 사용할 컬럼 불러오기
total_df = df_t
total_df = pd.DataFrame(total_df)
#total_df = total_df[total_df.columns.drop('일수')]
#total_df = total_df[total_df.columns.drop('합계')]
total_df = pd.merge(total_df,total_csi, how='left', left_index=True, right_index=True)
#total_df = pd.concat([total_df,total_csi],axis=1).reindex(total_csi.index)
total_df = total_df[['전자상거래/통신판매', '식료품','의류/잡화', '연료','가구/가전', '의료/보건', 
                     '자동차', '여행/교통', '스포츠/오락/여가', '서적/문구', '교육','숙박','음식점',
                     '공과금/개인및전문서비스', '금융/보험','소비자물가지수','소매판매지수','국고채_3년_평균',
                     '국고채_5년_평균','국고채_10년_평균','회사채_3년_평균','CD_91몰_평균','콜금리_1일몰_평균',
                     '기준금리']]
total_df.tail(28)

,전자상거래/통신판매,식료품,의류/잡화,연료,가구/가전,의료/보건,자동차,여행/교통,스포츠/오락/여가,서적/문구,...,금융/보험,소비자물가지수,소매판매지수,국고채_3년_평균,국고채_5년_평균,국고채_10년_평균,회사채_3년_평균,CD_91몰_평균,콜금리_1일몰_평균,기준금리
날짜,,,,,,,,,,,,,,,,,,,,,
2020-01,87087.68,10559.30,10246.05,27271.85,12140.98,37261.44,20187.86,11670.49,8983.18,2878.41,...,19345.07,100.09,111.8,1.37,1.48,1.66,1.96,1.47,1.27,1.25
2020-02,87127.99,6770.43,8575.23,24160.52,12097.46,34634.76,18056.65,5369.30,7167.26,2566.50,...,19009.49,100.16,97.8,1.25,1.36,1.54,1.85,1.42,1.24,1.25
2020-03,93566.47,7722.36,7902.72,23330.11,12693.07,31049.28,28101.92,2541.44,7247.17,2440.56,...,21144.17,99.94,106.9,1.09,1.27,1.49,1.84,1.23,0.98,0.75
2020-04,89536.50,7877.75,9142.46,21179.83,12616.47,33411.03,30818.97,3876.08,8868.53,2525.93,...,20396.24,99.50,108.9,1.02,1.26,1.50,2.15,1.10,0.74,0.75
2020-05,93625.55,9141.05,12415.68,20510.30,15450.67,35217.11,32935.40,5048.82,11860.98,2798.60,...,20678.63,99.44,118.4,0.88,1.13,1.39,2.18,1.02,0.70,0.50
2020-06,95115.82,7438.81,10807.62,21052.99,15531.45,34893.29,35593.17,5452.98,10619.86,2563.20,...,21084.95,99.71,116.9,0.85,1.13,1.39,2.22,0.79,0.48,0.50
2020-07,95903.06,7627.20,9559.78,21937.48,13544.35,36703.80,30690.80,6176.38,10074.58,2592.27,...,21790.82,99.63,110.9,0.83,1.09,1.36,2.22,0.79,0.48,0.50
2020-08,97260.21,8161.18,8317.41,22350.01,15713.85,34372.63,25045.89,5447.16,9273.81,2516.71,...,20611.84,100.19,111.7,0.83,1.09,1.37,2.19,0.68,0.50,0.50
2020-09,102942.57,10934.82,8849.61,21612.10,13028.34,35674.69,31292.65,4654.39,8251.40,2500.34,...,20922.42,100.74,118.0,0.91,1.19,1.50,2.24,0.63,0.48,0.50
2020-10,100389.20,8784.12,10782.09,21838.87,12298.10,33624.89,29582.12,5673.77,11553.16,2370.57,...,21271.85,100.18,115.8,0.91,1.20,1.51,2.24,0.63,0.51,0.50
2020-11,106573.90,8613.71,10338.01,22013.57,13675.91,34309.68,31254.46,5928.46,10455.59,2358.26,...,21049.31,100.09,119.0,0.97,1.30,1.61,2.25,0.66,0.49,0.50
2020-12,114122.35,9031.39,8928.98,23053.68,12162.25,36728.04,31209.01,4228.03,6158.71,2643.21,...,22594.55,100.33,119.1,0.97,1.32,1.68,2.21,0.66,0.51,0.50
2021-01,110777.75,9036.92,8018.10,23411.64,13803.54,36802.39,27211.75,4398.47,5202.53,2614.48,...,21184.62,101.04,112.2,0.98,1.32,1.73,2.14,0.68,0.49,0.50
2021-02,101210.87,9908.90,8007.32,22634.11,12143.92,33232.71,23152.00,4668.65,7199.14,2375.98,...,20007.66,101.58,106.2,1.00,1.35,1.85,2.06,0.73,0.49,0.50
2021-03,114774.14,8248.19,10372.62,25940.80,13815.00,37709.43,31053.94,5830.00,10656.32,3186.81,...,23468.41,101.84,119.5,1.13,1.55,2.04,2.09,0.75,0.49,0.50
2021-04,110523.10,8484.01,10257.64,25632.59,12407.52,37627.95,30774.32,6057.47,11071.33,2563.77,...,22079.96,101.98,118.9,1.14,1.58,2.04,1.98,0.74,0.48,0.50
2021-05,117532.68,9490.07,10716.23,25855.68,13979.76,36396.42,29620.71,6237.21,12083.35,2679.25,...,22084.42,102.05,122.8,1.13,1.65,2.13,1.89,0.68,0.48,0.50
2021-06,113328.76,8439.26,10310.48,26071.19,13288.89,38259.10,30555.01,6603.71,11803.69,2471.24,...,22751.21,102.05,119.5,1.30,1.70,2.10,1.91,0.66,0.51,0.50
2021-07,119218.32,8524.05,9526.45,28011.80,15172.72,39414.12,30105.13,5774.79,10756.75,2695.02,...,23167.49,102.26,120.2,1.42,1.69,1.98,1.89,0.69,0.53,0.50
2021-08,117620.70,9211.61,8471.57,27285.56,13833.83,37413.96,25464.55,5453.71,10188.12,2552.77,...,22229.94,102.75,116.5,1.41,1.65,1.91,1.84,0.77,0.56,0.75
2021-09,117337.27,12657.04,10084.59,26271.40,11849.15,35499.24,23221.81,5848.41,11020.20,2676.22,...,22154.25,103.17,122.7,1.52,1.79,2.06,1.95,0.98,0.77,0.75
2021-10,124986.77,9779.25,12101.18,29280.12,13068.48,40334.02,27576.06,6979.87,13091.77,2652.99,...,22704.33,103.35,125.0,1.84,2.15,2.40,2.30,1.08,0.74,0.75
2021-11,129889.75,9752.18,11398.54,30074.86,13012.22,38798.53,28625.30,7719.92,12338.07,2510.15,...,22889.94,103.87,124.7,1.95,2.17,2.36,2.49,1.17,0.80,1.00
2021-12,132006.30,10014.39,10822.68,30042.62,11529.33,40950.31,29960.16,6208.72,9748.01,2975.90,...,24112.50,104.04,127.2,1.80,1.98,2.19,2.41,1.27,1.01,1.00
2022-01,131621.64,12855.90,9770.24,29465.30,12837.68,41838.21,23262.35,6424.24,8512.42,2825.23,...,22435.69,104.69,117.5,2.06,2.28,2.49,2.63,1.39,1.19,1.25
2022-02,119029.37,7986.69,7934.06,26321.30,11875.13,36520.65,23216.11,5399.46,7841.77,2362.28,...,21303.98,105.30,107.9,2.29,2.50,2.69,2.87,1.50,1.22,1.25
2022-03,134751.97,8896.80,9799.52,31667.00,12371.40,42319.14,26042.56,6810.52,10963.02,3313.79,...,25145.71,106.06,122.0,2.37,2.60,2.78,3.03,1.50,1.24,1.25
2022-04,130324.09,9477.90,11200.08,33572.21,12008.97,40913.24,28247.88,8846.07,13297.52,2667.91,...,23396.79,106.85,119.4,2.94,3.14,3.22,3.63,1.64,1.30,1.50

In [15]:
# 컬럼별 등락률 계산

col_list = []
col_list.append([col for col in total_df])

total_df1 = pd.DataFrame()

for i in col_list:
    total_df1[i] = total_df[i].pct_change()
    
total_df1 = total_df1.iloc[1:]
total_df1.head(10)

,전자상거래/통신판매,식료품,의류/잡화,연료,가구/가전,의료/보건,자동차,여행/교통,스포츠/오락/여가,서적/문구,...,금융/보험,소비자물가지수,소매판매지수,국고채_3년_평균,국고채_5년_평균,국고채_10년_평균,회사채_3년_평균,CD_91몰_평균,콜금리_1일몰_평균,기준금리
날짜,,,,,,,,,,,,,,,,,,,,,
2012-12,0.027613,0.024488,-0.031449,-0.019097,-0.122218,-0.049408,0.192904,0.071612,-0.135839,0.118333,...,-0.008377,0.001782,0.023590,0.017857,0.038328,0.046823,-0.006024,0.010526,0.000000,0.000000
2013-01,-0.047579,0.026437,-0.156039,-0.023171,-0.006880,0.134797,-0.309056,0.059998,-0.113972,-0.069215,...,-0.010249,0.005999,-0.086172,-0.035088,-0.040268,-0.025559,-0.030303,-0.006944,0.003636,0.000000
2013-02,-0.138342,0.096626,-0.068648,-0.088923,-0.023821,-0.133135,0.037585,-0.141945,-0.150124,-0.107126,...,-0.087602,0.003343,-0.048246,-0.018182,-0.010490,-0.003279,-0.043750,-0.010490,-0.003623,0.000000
2013-03,0.085685,-0.133374,0.183154,0.112232,0.270387,0.087816,0.223547,0.045869,0.355010,0.471158,...,0.078341,-0.000924,0.078341,-0.037037,-0.049470,-0.042763,-0.035948,-0.007067,-0.003636,0.000000
2013-04,0.045225,0.001931,-0.009763,-0.027114,-0.081842,-0.038601,0.004995,0.060437,0.028387,-0.204835,...,0.025264,-0.001388,-0.018162,-0.019231,-0.022305,-0.024055,-0.013559,-0.003559,0.003650,0.000000
2013-05,0.030078,0.118197,0.153771,-0.004201,0.168977,0.031620,0.038395,0.102658,0.140511,-0.104216,...,-0.004087,0.000000,0.052231,0.015686,0.019011,0.021127,0.017182,-0.028571,-0.072727,-0.090909
2013-06,-0.077858,-0.080582,-0.153165,-0.039128,-0.016246,-0.057881,-0.173750,-0.076668,-0.125799,-0.079599,...,-0.073479,-0.001217,-0.036194,0.108108,0.149254,0.141379,0.094595,-0.011029,-0.023529,0.000000
2013-07,0.150429,-0.006796,-0.058976,0.060194,0.114377,0.063149,0.090798,0.210762,-0.045473,0.160407,...,0.163193,0.002146,0.022532,0.013937,0.032468,0.048338,0.043210,-0.003717,-0.004016,0.000000
2013-08,-0.134360,0.079289,-0.148741,0.063514,-0.083091,-0.007181,-0.099600,-0.127611,-0.018110,-0.088365,...,-0.103674,0.003541,-0.044071,0.010309,0.025157,0.040346,-0.014793,-0.007463,0.008065,0.000000
2013-09,0.045611,0.309180,0.200553,-0.092699,-0.218906,-0.111934,-0.140947,-0.094780,0.027542,0.014355,...,0.010495,0.001941,0.031833,-0.013605,-0.027607,-0.022161,-0.012012,0.000000,0.000000,0.000000

### 정규성 검정

In [176]:
from scipy import stats
from scipy.stats import shapiro

# 등락률 컬럼만 추출해서 pvalue 구하는 함수
def shap_pct(df_name):
    pct_colus = []
    pct_colus.append([col for col in df_name])
    for i in pct_colus:
        for j in i:
            shapiro_test = shapiro(df_name[j])
            print(j, "의 pvalue:", shapiro_test.pvalue)

In [177]:
shap_pct(total_df1)

전자상거래/통신판매 의 pvalue: 0.3099466860294342
식료품 의 pvalue: 0.18268708884716034
의류/잡화 의 pvalue: 0.002145733218640089
연료 의 pvalue: 0.5080863237380981
가구/가전 의 pvalue: 0.04512302577495575
의료/보건 의 pvalue: 0.33753088116645813
자동차 의 pvalue: 0.552711546421051
여행/교통 의 pvalue: 0.007531149312853813
스포츠/오락/여가 의 pvalue: 5.428668373497203e-06
서적/문구 의 pvalue: 3.1865913570072735e-06
교육 의 pvalue: 0.016805186867713928
숙박 의 pvalue: 0.26351138949394226
음식점 의 pvalue: 0.004374518990516663
공과금/개인및전문서비스 의 pvalue: 0.037681806832551956
금융/보험 의 pvalue: 0.003127526259049773
소비자물가지수 의 pvalue: 0.14466038346290588
소매판매지수 의 pvalue: 0.5582879185676575
국고채_3년_평균 의 pvalue: 0.031163373962044716
국고채_5년_평균 의 pvalue: 0.001721347332932055
국고채_10년_평균 의 pvalue: 0.008204905316233635
회사채_3년_평균 의 pvalue: 0.08730660378932953
CD_91몰_평균 의 pvalue: 8.520189709315673e-08
콜금리_1일몰_평균 의 pvalue: 3.0223399737766554e-12
기준금리 의 pvalue: 4.093405302219022e-16

In [178]:
total_df1 = total_df1.reset_index('날짜')
df_book = total_df1[['날짜','서적/문구','소비자물가지수','소매판매지수']]

In [179]:
month_df = df_book.copy()
month_df = month_df[['날짜','서적/문구']]
month_df.head()

        날짜     서적/문구
0  2012-12  0.118333
1  2013-01 -0.069215
2  2013-02 -0.107126
3  2013-03  0.471158
4  2013-04 -0.204835

In [180]:
month_df["날짜"] = month_df["날짜"].astype(str)
# 동월 전체 평균
month_df["서적/문구"][month_df["날짜"].str.endswith("12")].mean()

0.16692383500859187

In [181]:
pre_mean = month_df["서적/문구"].mean()

In [182]:
# 각 동월 전체 평균 리스트 저장

month_list = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
month_mean = []
for i in month_list:
    month_mean.append(month_df["서적/문구"][month_df["날짜"].str.endswith(i)].mean())
month_mean

[-0.09377506840603309,
 -0.08125907698439297,
 0.45989723679854866,
 -0.2637166991734027,
 -0.029655912467158898,
 -0.06021902317911471,
 0.13937164065191374,
 -0.060013373299463164,
 0.01768928819256829,
 -0.049443423235457855,
 0.01788438623691121,
 0.16692383500859187]

In [183]:
# "동월_평균_등락률" 컬럼 생성 및 값 저장

month_df["동월_평균_등락률"] = ""
for i in month_list:
        month_df["동월_평균_등락률"][month_df["날짜"].str.endswith(i)]  = month_df["서적/문구"][month_df["날짜"].str.endswith(i)].mean()
month_df.head(13)

C:\Users\82104\AppData\Local\Temp\ipykernel_22320\4237456934.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  month_df["동월_평균_등락률"][month_df["날짜"].str.endswith(i)]  = month_df["서적/문구"][month_df["날짜"].str.endswith(i)].mean()

         날짜     서적/문구 동월_평균_등락률
0   2012-12  0.118333  0.166924
1   2013-01 -0.069215 -0.093775
2   2013-02 -0.107126 -0.081259
3   2013-03  0.471158  0.459897
4   2013-04 -0.204835 -0.263717
5   2013-05 -0.104216 -0.029656
6   2013-06 -0.079599 -0.060219
7   2013-07  0.160407  0.139372
8   2013-08 -0.088365 -0.060013
9   2013-09  0.014355  0.017689
10  2013-10 -0.011677 -0.049443
11  2013-11  0.014116  0.017884
12  2013-12  0.168430  0.166924

In [184]:
# 동월별 양수 음수 등락률 평균값
import numpy as np

plus = [0.166924,0.459897,0.139372,0.017689,0.017884]
minus = [-0.093775,-0.081259,-0.263717,-0.029656,-0.060219,-0.060013,-0.049443]

# 평균 구하기
average_plus = np.mean(plus)
average_minus = np.mean(minus)

In [185]:
print(average_plus)
print(average_minus)

0.16035319999999997
-0.09115457142857143

In [186]:
# "전체_평균_대비" 컬럼 생성 및 값 저장

month_df["전체_평균_대비"] = ""

# 동월 평균 등락률이 전체 평균 보다 높거나 같으면 1, 낮으면 0
for i in range(0, 85):
    if month_df.loc[i, "동월_평균_등락률"] >= 0:
        if month_df.loc[i, "동월_평균_등락률"] >= average_plus:
            month_df.loc[i, "전체_평균_대비"] = 1
        else:
            month_df.loc[i, "전체_평균_대비"] = 0
    elif month_df.loc[i, "동월_평균_등락률"] < 0:
        if month_df.loc[i, "동월_평균_등락률"] >= average_minus:
            month_df.loc[i, "전체_평균_대비"] = 1
        else:
            month_df.loc[i, "전체_평균_대비"] = 0

month_df.tail()

         날짜     서적/문구 동월_평균_등락률 전체_평균_대비
80  2019-08 -0.016262 -0.060013        1
81  2019-09 -0.024028  0.017689        0
82  2019-10 -0.033313 -0.049443        1
83  2019-11  0.021241  0.017884        0
84  2019-12  0.121899  0.166924        1

In [187]:
df_book["동월_평균_등락률"] = month_df["동월_평균_등락률"]
df_book["전체_평균_대비"] = month_df["전체_평균_대비"]

C:\Users\82104\AppData\Local\Temp\ipykernel_22320\1541011350.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_book["동월_평균_등락률"] = month_df["동월_평균_등락률"]
C:\Users\82104\AppData\Local\Temp\ipykernel_22320\1541011350.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_book["전체_평균_대비"] = month_df["전체_평균_대비"]

In [188]:
df_book

         날짜     서적/문구   소비자물가지수    소매판매지수 동월_평균_등락률 전체_평균_대비
0   2012-12  0.118333  0.001782  0.023590  0.166924        1
1   2013-01 -0.069215  0.005999 -0.086172 -0.093775        0
2   2013-02 -0.107126  0.003343 -0.048246 -0.081259        1
3   2013-03  0.471158 -0.000924  0.078341  0.459897        1
4   2013-04 -0.204835 -0.001388 -0.018162 -0.263717        0
5   2013-05 -0.104216  0.000000  0.052231 -0.029656        1
6   2013-06 -0.079599 -0.001217 -0.036194 -0.060219        1
7   2013-07  0.160407  0.002146  0.022532  0.139372        0
8   2013-08 -0.088365  0.003541 -0.044071 -0.060013        1
9   2013-09  0.014355  0.001941  0.031833  0.017689        0
10  2013-10 -0.011677 -0.003051  0.032979 -0.049443        1
11  2013-11  0.014116 -0.000193  0.016478  0.017884        0
12  2013-12  0.168430  0.001214  0.012158  0.166924        1
13  2014-01 -0.103812  0.005374 -0.035035 -0.093775        0
14  2014-02 -0.081359  0.002667 -0.100622 -0.081259        1
15  2014-03  0.459274  0.001841  0.103806  0.459897        1
16  2014-04 -0.286140  0.000648 -0.033438 -0.263717        0
17  2014-05 -0.021034  0.001645  0.060541 -0.029656        1
18  2014-06 -0.091243 -0.001282 -0.036697 -0.060219        1
19  2014-07  0.192122  0.001464  0.020106  0.139372        0
20  2014-08 -0.068261  0.001748 -0.024896 -0.060013        1
21  2014-09  0.020185 -0.000645  0.018085  0.017689        0
22  2014-10 -0.035319 -0.003016  0.017764 -0.049443        1
23  2014-11  0.036877 -0.002017  0.026694  0.017884        0
24  2014-12  0.142098 -0.000096  0.052000  0.166924        1
25  2015-01 -0.075154  0.006776 -0.104563 -0.093775        0
26  2015-02 -0.116567 -0.000592 -0.013800 -0.081259        1
27  2015-03  0.514840  0.000095  0.067815  0.459897        1
28  2015-04 -0.262698  0.000307 -0.005040 -0.263717        0
29  2015-05 -0.046091  0.002801  0.039514 -0.029656        1
30  2015-06 -0.090228  0.000200 -0.074074 -0.060219        1
31  2015-07  0.190268  0.001802  0.030526  0.139372        0
32  2015-08 -0.080040  0.001399 -0.023493 -0.060013        1
33  2015-09  0.016307 -0.002594  0.069038  0.017689        0
34  2015-10 -0.021849  0.000000  0.040117 -0.049443        1
35  2015-11 -0.061074 -0.001895  0.000000  0.017884        0
36  2015-12  0.281181  0.002996  0.025400  0.166924        1
37  2016-01 -0.111393  0.001704 -0.086239 -0.093775        0
38  2016-02 -0.075779  0.004284 -0.040161 -0.081259        1
39  2016-03  0.455817 -0.002583  0.093096  0.459897        1
40  2016-04 -0.284409  0.001887 -0.022967 -0.263717        0
41  2016-05 -0.030636  0.000596  0.050930 -0.029656        1
42  2016-06 -0.033689 -0.000199 -0.036347 -0.060219        1
43  2016-07  0.145196 -0.001883 -0.012573  0.139372        0
44  2016-08 -0.085173  0.002578 -0.012733 -0.060013        1
45  2016-09  0.009137  0.005958  0.013889  0.017689        0
46  2016-10 -0.023686  0.001371  0.060665 -0.049443        1
47  2016-11  0.019742 -0.001473  0.006458  0.017884        0
48  2016-12  0.164018  0.001091  0.019248  0.166924        1
49  2017-01 -0.140694  0.010629 -0.071043 -0.093775        0
50  2017-02 -0.005742  0.002732 -0.078412 -0.081259        1
51  2017-03  0.411053 -0.000686  0.107143  0.459897        1
52  2017-04 -0.264739 -0.001261 -0.014231 -0.263717        0
53  2017-05 -0.035323  0.001067  0.035611 -0.029656        1
54  2017-06 -0.030183 -0.002132 -0.031599 -0.060219        1
55  2017-07  0.109307  0.001654  0.006718  0.139372        0
56  2017-08 -0.050647  0.005733 -0.034318 -0.060013        1
57  2017-09  0.077957  0.001163  0.080948  0.017689        0
58  2017-10 -0.167283 -0.000968 -0.013699 -0.049443        1
59  2017-11  0.075560 -0.007443  0.064815  0.017884        0
60  2017-12  0.179838  0.003606 -0.018261  0.166924        1
61  2018-01 -0.114661  0.004176 -0.067316 -0.093775        0
62  2018-02 -0.075422  0.007635 -0.034188 -0.081259        1
63  2018-03  0.477393 -0.001052  0.114061  0.459897        1
64  2018-04 -0.277346  0.001823 -0.030009 -0.263717        0
65  2018-05  0.023894  0.000485  0.026388 -0.029656        1
66  2018-06 -0.052572 -0.002021 -0.036348 -0.060219        1
67  2018-07  0.100549 -0.001913  0.019319  0.139372        0
68  2018-08 -0.031346  0.008845 -0.034296 -0.060013        1
69  2018-09  0.009911  0.007631  0.028037  0.017689        0
70  2018-10 -0.052978 -0.001796  0.032727 -0.049443        1
71  2018-11  0.018729 -0.007107  0.022887  0.017884        0
72  2018-12  0.159593 -0.003443  0.001721  0.166924        1
73  2019-01 -0.041497 -0.001051 -0.056701 -0.093775        0
74  2019-02 -0.106819  0.004318 -0.091075 -0.081259        1
75  2019-03  0.429745 -0.001913  0.162325  0.459897        1
76  2019-04 -0.265850  0.003632 -0.039655 -0.263717        0
77  2019-05  0.005815  0.001719  0.046679 -0.029656        1
78  2019-06 -0.044019 -0.001616 -0.056604 -0.060219        1
79  2019-07  0.077752 -0.003056  0.004545  0.139372        0
80  2019-08 -0.016262  0.002400  0.009050 -0.060013        1
81  2019-09 -0.024028  0.003711  0.016143  0.017689        0
82  2019-10 -0.033313  0.002475  0.021183 -0.049443        1
83  2019-11  0.021241 -0.005598  0.040622  0.017884        0
84  2019-12  0.121899  0.002392  0.009967  0.166924        1

In [189]:
pd.options.display.max_rows = None

In [190]:
df_book.describe()

           서적/문구    소비자물가지수     소매판매지수
count  85.000000  85.000000  85.000000
mean    0.015444   0.000952   0.003923
std     0.175948   0.003223   0.051923
min    -0.286140  -0.007443  -0.104563
25%    -0.080040  -0.001261  -0.034296
50%    -0.024028   0.001091   0.009050
75%     0.077957   0.002578   0.032727
max     0.514840   0.010629   0.162325

In [191]:
import numpy as np

df_book["날짜"] = df_book["날짜"].astype(str)
df_book["소비"] = ""

for i in range(0, 13):
    for j in range(12, 85):
        if df_book.loc[i, "날짜"].endswith("03"):
            df_book.loc[i, "소비"] = 1
        else:
            if df_book.loc[i,"서적/문구"] > 0: 
                if df_book.loc[i,"소매판매지수"] >= df_book["소매판매지수"].quantile(q=0.5):
                    df_book.loc[i,"소비"] = 1
                elif df_book.loc[i,"소매판매지수"] >= df_book["소매판매지수"].quantile(q=0.25):
                    if df_book.loc[i,"소비자물가지수"] <= df_book["소비자물가지수"].quantile(q=0.75):
                        df_book.loc[i,"소비"] = 1
                    else:
                        df_book.loc[i,"소비"] = 0
                elif df_book.loc[i,"소매판매지수"] < df_book["소매판매지수"].quantile(q=0.25):
                    df_book.loc[i,"소비"] = 0

            elif df_book.loc[i, "서적/문구"] <= 0:
                if df_book.loc[i,"소매판매지수"] <= df_book["소매판매지수"].quantile(q=0.75):
                    df_book.loc[i,"소비"] = 0
                elif df_book.loc[i,"소매판매지수"] > df_book["소매판매지수"].quantile(q=0.75):
                    if df_book.loc[i,"소비자물가지수"] > df_book["소비자물가지수"].quantile(q=0.5):
                        df_book.loc[i,"소비"] = 0
                    else:
                        df_book.loc[i,"소비"] = 1
                    
                    
        if df_book["서적/문구"].loc[j] > 0:
            if df_book['서적/문구'].loc[j-12] > 0:
                if df_book["전체_평균_대비"].loc[j] == 1:
                    df_book.loc[j,"소비"] = 1
                elif df_book["전체_평균_대비"].loc[j] != 1:
                    if df_book.loc[j,'소매판매지수'] >= 0.009050:
                        if df_book.loc[j,'소비자물가지수'] > 0.001091:
                            df_book.loc[j,"소비"] = 0
                        else:
                            df_book.loc[j,"소비"] = 1
                    elif df_book.loc[j,'소매판매지수'] < 0.009050:
                        df_book.loc[j,"소비"] = 0
                        
            elif df_book['서적/문구'].loc[j-12] <= 0:
                if df_book["전체_평균_대비"].loc[j] == 1:
                    df_book.loc[j,'소비'] = 1
                elif df_book["전체_평균_대비"].loc[j] != 1:
                    if df_book.loc[j,'소매판매지수'] >= 0.009050:
                        if df_book.loc[j,'소비자물가지수'] > 0.001091:
                            df_book.loc[j,'소비'] = 0
                        else:
                            df_book.loc[j,'소비'] = 1
                    else:
                        df_book.loc[j,'소비'] = 0
                    
        elif df_book["서적/문구"].loc[j] <= 0:
            if df_book['서적/문구'].loc[j-12] <= 0:
                if df_book["전체_평균_대비"].loc[j] == 0:
                    df_book.loc[j,"소비"] =0
                elif df_book["전체_평균_대비"].loc[j] != 0:
                    if df_book.loc[j,'소매판매지수'] >= 0.009050:
                        if df_book.loc[j,'소비자물가지수'] > 0.001091:
                            df_book.loc[j,'소비'] = 0
                        else:
                            df_book.loc[j,'소비'] = 1
                    else:
                        df_book.loc[j,'소비'] = 0
                        
            elif df_book['서적/문구'].loc[j-12] >= 0:
                if df_book.loc[j,'전체_평균_대비'] == 0:
                    df_book.loc[j,'소비'] = 0
                elif df_book.loc[j,'전체_평균_대비'] != 0:
                    if df_book.loc[j,'소매판매지수'] >= 0.009050:
                        if df_book.loc[j,'소비자물가지수'] > 0.001091:
                            df_book.loc[j,'소비'] = 0
                        else:
                            df_book.loc[j,'소비'] = 1
                    else:
                        df_book.loc[j,'소비'] = 0
                        
df_book

C:\Users\82104\AppData\Local\Temp\ipykernel_22320\2273680911.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_book["날짜"] = df_book["날짜"].astype(str)
C:\Users\82104\AppData\Local\Temp\ipykernel_22320\2273680911.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_book["소비"] = ""

         날짜     서적/문구   소비자물가지수    소매판매지수 동월_평균_등락률 전체_평균_대비 소비
0   2012-12  0.118333  0.001782  0.023590  0.166924        1  1
1   2013-01 -0.069215  0.005999 -0.086172 -0.093775        0  0
2   2013-02 -0.107126  0.003343 -0.048246 -0.081259        1  0
3   2013-03  0.471158 -0.000924  0.078341  0.459897        1  1
4   2013-04 -0.204835 -0.001388 -0.018162 -0.263717        0  0
5   2013-05 -0.104216  0.000000  0.052231 -0.029656        1  1
6   2013-06 -0.079599 -0.001217 -0.036194 -0.060219        1  0
7   2013-07  0.160407  0.002146  0.022532  0.139372        0  1
8   2013-08 -0.088365  0.003541 -0.044071 -0.060013        1  0
9   2013-09  0.014355  0.001941  0.031833  0.017689        0  1
10  2013-10 -0.011677 -0.003051  0.032979 -0.049443        1  1
11  2013-11  0.014116 -0.000193  0.016478  0.017884        0  1
12  2013-12  0.168430  0.001214  0.012158  0.166924        1  1
13  2014-01 -0.103812  0.005374 -0.035035 -0.093775        0  0
14  2014-02 -0.081359  0.002667 -0.100622 -0.081259        1  0
15  2014-03  0.459274  0.001841  0.103806  0.459897        1  1
16  2014-04 -0.286140  0.000648 -0.033438 -0.263717        0  0
17  2014-05 -0.021034  0.001645  0.060541 -0.029656        1  0
18  2014-06 -0.091243 -0.001282 -0.036697 -0.060219        1  0
19  2014-07  0.192122  0.001464  0.020106  0.139372        0  0
20  2014-08 -0.068261  0.001748 -0.024896 -0.060013        1  0
21  2014-09  0.020185 -0.000645  0.018085  0.017689        0  1
22  2014-10 -0.035319 -0.003016  0.017764 -0.049443        1  1
23  2014-11  0.036877 -0.002017  0.026694  0.017884        0  1
24  2014-12  0.142098 -0.000096  0.052000  0.166924        1  1
25  2015-01 -0.075154  0.006776 -0.104563 -0.093775        0  0
26  2015-02 -0.116567 -0.000592 -0.013800 -0.081259        1  0
27  2015-03  0.514840  0.000095  0.067815  0.459897        1  1
28  2015-04 -0.262698  0.000307 -0.005040 -0.263717        0  0
29  2015-05 -0.046091  0.002801  0.039514 -0.029656        1  0
30  2015-06 -0.090228  0.000200 -0.074074 -0.060219        1  0
31  2015-07  0.190268  0.001802  0.030526  0.139372        0  0
32  2015-08 -0.080040  0.001399 -0.023493 -0.060013        1  0
33  2015-09  0.016307 -0.002594  0.069038  0.017689        0  1
34  2015-10 -0.021849  0.000000  0.040117 -0.049443        1  1
35  2015-11 -0.061074 -0.001895  0.000000  0.017884        0  0
36  2015-12  0.281181  0.002996  0.025400  0.166924        1  1
37  2016-01 -0.111393  0.001704 -0.086239 -0.093775        0  0
38  2016-02 -0.075779  0.004284 -0.040161 -0.081259        1  0
39  2016-03  0.455817 -0.002583  0.093096  0.459897        1  1
40  2016-04 -0.284409  0.001887 -0.022967 -0.263717        0  0
41  2016-05 -0.030636  0.000596  0.050930 -0.029656        1  1
42  2016-06 -0.033689 -0.000199 -0.036347 -0.060219        1  0
43  2016-07  0.145196 -0.001883 -0.012573  0.139372        0  0
44  2016-08 -0.085173  0.002578 -0.012733 -0.060013        1  0
45  2016-09  0.009137  0.005958  0.013889  0.017689        0  0
46  2016-10 -0.023686  0.001371  0.060665 -0.049443        1  0
47  2016-11  0.019742 -0.001473  0.006458  0.017884        0  0
48  2016-12  0.164018  0.001091  0.019248  0.166924        1  1
49  2017-01 -0.140694  0.010629 -0.071043 -0.093775        0  0
50  2017-02 -0.005742  0.002732 -0.078412 -0.081259        1  0
51  2017-03  0.411053 -0.000686  0.107143  0.459897        1  1
52  2017-04 -0.264739 -0.001261 -0.014231 -0.263717        0  0
53  2017-05 -0.035323  0.001067  0.035611 -0.029656        1  1
54  2017-06 -0.030183 -0.002132 -0.031599 -0.060219        1  0
55  2017-07  0.109307  0.001654  0.006718  0.139372        0  0
56  2017-08 -0.050647  0.005733 -0.034318 -0.060013        1  0
57  2017-09  0.077957  0.001163  0.080948  0.017689        0  0
58  2017-10 -0.167283 -0.000968 -0.013699 -0.049443        1  0
59  2017-11  0.075560 -0.007443  0.064815  0.017884        0  1
60  2017-12  0.179838  0.003606 -0.018261  0.166924        1  1
61  2018-01 -0.114661  0.004176 -0.067316 -0.093775        0  0
62  2018-02 -0.075422  0.007635 -0.034188 -0.081259        1  0
63  2018-03  0.477393 -0.001052  0.114061  0.459897        1  1
64  2018-04 -0.277346  0.001823 -0.030009 -0.263717        0  0
65  2018-05  0.023894  0.000485  0.026388 -0.029656        1  1
66  2018-06 -0.052572 -0.002021 -0.036348 -0.060219        1  0
67  2018-07  0.100549 -0.001913  0.019319  0.139372        0  1
68  2018-08 -0.031346  0.008845 -0.034296 -0.060013        1  0
69  2018-09  0.009911  0.007631  0.028037  0.017689        0  0
70  2018-10 -0.052978 -0.001796  0.032727 -0.049443        1  1
71  2018-11  0.018729 -0.007107  0.022887  0.017884        0  1
72  2018-12  0.159593 -0.003443  0.001721  0.166924        1  1
73  2019-01 -0.041497 -0.001051 -0.056701 -0.093775        0  0
74  2019-02 -0.106819  0.004318 -0.091075 -0.081259        1  0
75  2019-03  0.429745 -0.001913  0.162325  0.459897        1  1
76  2019-04 -0.265850  0.003632 -0.039655 -0.263717        0  0
77  2019-05  0.005815  0.001719  0.046679 -0.029656        1  1
78  2019-06 -0.044019 -0.001616 -0.056604 -0.060219        1  0
79  2019-07  0.077752 -0.003056  0.004545  0.139372        0  0
80  2019-08 -0.016262  0.002400  0.009050 -0.060013        1  0
81  2019-09 -0.024028  0.003711  0.016143  0.017689        0  0
82  2019-10 -0.033313  0.002475  0.021183 -0.049443        1  0
83  2019-11  0.021241 -0.005598  0.040622  0.017884        0  1
84  2019-12  0.121899  0.002392  0.009967  0.166924        1  1

In [192]:
df_book[df_book["소비"]==1]

         날짜     서적/문구   소비자물가지수    소매판매지수 동월_평균_등락률 전체_평균_대비 소비
0   2012-12  0.118333  0.001782  0.023590  0.166924        1  1
3   2013-03  0.471158 -0.000924  0.078341  0.459897        1  1
5   2013-05 -0.104216  0.000000  0.052231 -0.029656        1  1
7   2013-07  0.160407  0.002146  0.022532  0.139372        0  1
9   2013-09  0.014355  0.001941  0.031833  0.017689        0  1
10  2013-10 -0.011677 -0.003051  0.032979 -0.049443        1  1
11  2013-11  0.014116 -0.000193  0.016478  0.017884        0  1
12  2013-12  0.168430  0.001214  0.012158  0.166924        1  1
15  2014-03  0.459274  0.001841  0.103806  0.459897        1  1
21  2014-09  0.020185 -0.000645  0.018085  0.017689        0  1
22  2014-10 -0.035319 -0.003016  0.017764 -0.049443        1  1
23  2014-11  0.036877 -0.002017  0.026694  0.017884        0  1
24  2014-12  0.142098 -0.000096  0.052000  0.166924        1  1
27  2015-03  0.514840  0.000095  0.067815  0.459897        1  1
33  2015-09  0.016307 -0.002594  0.069038  0.017689        0  1
34  2015-10 -0.021849  0.000000  0.040117 -0.049443        1  1
36  2015-12  0.281181  0.002996  0.025400  0.166924        1  1
39  2016-03  0.455817 -0.002583  0.093096  0.459897        1  1
41  2016-05 -0.030636  0.000596  0.050930 -0.029656        1  1
48  2016-12  0.164018  0.001091  0.019248  0.166924        1  1
51  2017-03  0.411053 -0.000686  0.107143  0.459897        1  1
53  2017-05 -0.035323  0.001067  0.035611 -0.029656        1  1
59  2017-11  0.075560 -0.007443  0.064815  0.017884        0  1
60  2017-12  0.179838  0.003606 -0.018261  0.166924        1  1
63  2018-03  0.477393 -0.001052  0.114061  0.459897        1  1
65  2018-05  0.023894  0.000485  0.026388 -0.029656        1  1
67  2018-07  0.100549 -0.001913  0.019319  0.139372        0  1
70  2018-10 -0.052978 -0.001796  0.032727 -0.049443        1  1
71  2018-11  0.018729 -0.007107  0.022887  0.017884        0  1
72  2018-12  0.159593 -0.003443  0.001721  0.166924        1  1
75  2019-03  0.429745 -0.001913  0.162325  0.459897        1  1
77  2019-05  0.005815  0.001719  0.046679 -0.029656        1  1
83  2019-11  0.021241 -0.005598  0.040622  0.017884        0  1
84  2019-12  0.121899  0.002392  0.009967  0.166924        1  1

In [193]:
df_book.to_csv('rw.csv',encoding='utf-8')