### 전국 신용카드 승인금액

In [164]:
import pandas as pd

# csv파일 불러오기
df = pd.read_csv('./data/카드_전국.csv')
df.head()

,날짜,전국_합계,전국_종합소매,전국_ 백화점,전국_ 대형마트/유통전문점,전국_ 슈퍼마켓,전국_ 편의점,전국_ 면세점,전국_전자상거래/통신판매,전국_식료품,...,전국_오락/문화,전국_ 스포츠/오락/여가,전국_ 서적/문구,전국_교육,전국_숙박/음식,전국_ 숙박,전국_ 음식점,전국_공과금/개인 및 전문 서비스,전국_금융/보험,전국_기타
0,2012/11,299970.34,53558.49,13695.10,26123.23,10604.38,1826.54,1309.25,29166.45,4778.33,...,13142.50,10450.19,2692.31,8644.69,33317.61,2119.99,31197.62,25205.61,10618.86,18468.27
1,2012/12,310533.02,57731.17,14542.45,28802.59,11308.05,1810.70,1267.38,29971.83,4895.34,...,12041.55,9030.65,3010.90,8440.60,37410.08,2454.51,34955.56,25947.67,10529.91,19655.81
2,2013/01,296732.27,51384.80,11189.07,25640.42,11435.88,1778.78,1340.65,28545.80,5024.76,...,10803.91,8001.41,2802.50,8776.78,34309.86,2458.03,31851.83,30498.42,10421.99,19792.28
3,2013/02,267365.92,48141.86,9748.40,25035.42,10602.32,1652.60,1103.11,24596.71,5510.28,...,9302.49,6800.21,2502.28,8431.41,28779.93,1821.75,26958.18,25149.57,9509.00,18103.45
4,2013/03,295640.18,49572.79,10873.94,24769.86,10904.74,1877.38,1146.88,26704.28,4775.35,...,12895.59,9214.35,3681.25,8996.41,34196.47,1898.21,32298.26,25570.21,10253.94,19820.98

In [165]:
# 날짜 컬럼 "/" 제거
df["날짜"] = df["날짜"].str.replace("/", "")

# 날짜 컬럼 int 타입으로 변환
df["날짜"] = df["날짜"].astype(int)

# 날짜 데이터타임 변환 후 인덱스 변환
df["날짜"] = pd.to_datetime(df["날짜"], format='%Y%m')
df["날짜"] = df["날짜"].dt.strftime('%Y-%m')
df.set_index('날짜', inplace=True)

In [166]:
# 컬럼 맞추기
df.columns = df.columns.str.replace('_ ','_')
df.columns = df.columns.str.replace(' ','')
df.columns

Index(['전국_합계', '전국_종합소매', '전국_백화점', '전국_대형마트/유통전문점', '전국_슈퍼마켓', '전국_편의점',
       '전국_면세점', '전국_전자상거래/통신판매', '전국_식료품', '전국_일반식료품', '전국_건강보조식품',
       '전국_의류/잡화', '전국_의복/직물', '전국_복식잡화', '전국_시계/귀금속/안경', '전국_화장품', '전국_연료',
       '전국_가구/가전', '전국_가구', '전국_가전제품/정보통신기기', '전국_의료/보건', '전국_종합병원',
       '전국_일반병의원/기타의료기관', '전국_자동차', '전국_국산자동차신품', '전국_기타운송수단', '전국_자동차부품및정비',
       '전국_여행/교통', '전국_여행사/자동차임대', '전국_항공사', '전국_대중교통', '전국_오락/문화',
       '전국_스포츠/오락/여가', '전국_서적/문구', '전국_교육', '전국_숙박/음식', '전국_숙박', '전국_음식점',
       '전국_공과금/개인및전문서비스', '전국_금융/보험', '전국_기타'],
      dtype='object')

In [167]:
df.columns = ['합계', '종합소매', '백화점', '대형마트/유통전문점', '슈퍼마켓', '편의점',
       '면세점', '전자상거래/통신판매', '식료품', '일반식료품', '건강보조식품',
       '의류/잡화', '의복/직물', '복식잡화', '시계/귀금속/안경', '화장품', '연료',
       '가구/가전', '가구', '가전제품/정보통신기기', '의료/보건', '종합병원',
       '일반병의원/기타의료기관', '자동차', '국산자동차신품', '기타운송수단', '자동차부품및정비',
       '여행/교통', '여행사/자동차임대', '항공사', '대중교통', '오락/문화',
       '스포츠/오락/여가', '서적/문구', '교육', '숙박/음식', '숙박', '음식점',
       '공과금/개인및전문서비스', '금융/보험', '기타']

### 분류별 상품 나누기

In [168]:
# 합계 분류 하기
df_t = df[['종합소매','전자상거래/통신판매', '식료품','의류/잡화', 
'연료','가구/가전', '의료/보건', '자동차', '여행/교통', '스포츠/오락/여가', '서적/문구', '교육','숙박','음식점'
,'공과금/개인및전문서비스', '금융/보험']]
# 등락률 구하기
df_t1 = df[['종합소매','전자상거래/통신판매', '식료품','의류/잡화',
'연료','가구/가전', '의료/보건', '자동차', '여행/교통', '스포츠/오락/여가', '서적/문구', '교육','숙박','음식점'
,'공과금/개인및전문서비스', '금융/보험']].pct_change().round(2)

### 소비자 물가지수 불러오기

In [169]:
cpi_df = pd.read_csv('./csv/소비자물가지수_2020100__20220811151333.csv',encoding='cp949')

# 컬럼 문자열로 바꾸기
cpi_df["시점"] = cpi_df["시점"].astype(str)

# .10 이 .1로 변환된 걸 다시 재변환
cpi_df["시점"][cpi_df["시점"].str.endswith(".1")] = cpi_df["시점"][cpi_df["시점"].str.endswith(".1")]+"0"

# 컬럼명 변경
cpi_df.rename(columns={'전국' : '소비자물가지수'}, inplace=True)
# 날짜 맞추기
cpi_df = cpi_df.iloc[:-3]

# 데이터타임 변황 후 시점컬럼명 날짜로 바꾸기
cpi_df["시점"] = pd.to_datetime(cpi_df["시점"], format="%Y.%m")
cpi_df["시점"] = cpi_df["시점"].dt.strftime('%Y-%m')
cpi_df.rename(columns={"시점" : "날짜"}, inplace=True)
cpi_df.set_index('날짜', inplace=True)
cpi_df

C:\Users\82104\AppData\Local\Temp\ipykernel_22320\3132659229.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cpi_df["시점"][cpi_df["시점"].str.endswith(".1")] = cpi_df["시점"][cpi_df["시점"].str.endswith(".1")]+"0"
C:\Users\82104\AppData\Local\Temp\ipykernel_22320\3132659229.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cpi_df["시점"] = pd.to_datetime(cpi_df["시점"], format="%Y.%m")
C:\Users\82104\AppData\Local\Temp\ipykernel_22320\3132659229.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cpi_df["시점"] = cpi_df["시점"].dt.strftime('%Y-%m')
C:\Users\82104\AppData\Local\Temp\ipykernel_22320\3132659229.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cpi_df.rename(columns={"시점" : "날짜"}, inplace=True)

         소비자물가지수
날짜
2012-11   92.011
2012-12   92.175
2013-01   92.728
2013-02   93.038
2013-03   92.952
2013-04   92.823
2013-05   92.823
2013-06   92.710
2013-07   92.909
2013-08   93.238
2013-09   93.419
2013-10   93.134
2013-11   93.116
2013-12   93.229
2014-01   93.730
2014-02   93.980
2014-03   94.153
2014-04   94.214
2014-05   94.369
2014-06   94.248
2014-07   94.386
2014-08   94.551
2014-09   94.490
2014-10   94.205
2014-11   94.015
2014-12   94.006
2015-01   94.643
2015-02   94.587
2015-03   94.596
2015-04   94.625
2015-05   94.890
2015-06   94.909
2015-07   95.080
2015-08   95.213
2015-09   94.966
2015-10   94.966
2015-11   94.786
2015-12   95.070
2016-01   95.232
2016-02   95.640
2016-03   95.393
2016-04   95.573
2016-05   95.630
2016-06   95.611
2016-07   95.431
2016-08   95.677
2016-09   96.247
2016-10   96.379
2016-11   96.237
2016-12   96.342
2017-01   97.366
2017-02   97.632
2017-03   97.565
2017-04   97.442
2017-05   97.546
2017-06   97.338
2017-07   97.499
2017-08   98.058
2017-09   98.172
2017-10   98.077
2017-11   97.347
2017-12   97.698
2018-01   98.106
2018-02   98.855
2018-03   98.751
2018-04   98.931
2018-05   98.979
2018-06   98.779
2018-07   98.590
2018-08   99.462
2018-09  100.221
2018-10  100.041
2018-11   99.330
2018-12   98.988
2019-01   98.884
2019-02   99.311
2019-03   99.121
2019-04   99.481
2019-05   99.652
2019-06   99.491
2019-07   99.187
2019-08   99.425
2019-09   99.794
2019-10  100.041
2019-11   99.481
2019-12   99.719
2020-01  100.090
2020-02  100.160
2020-03   99.940
2020-04   99.500
2020-05   99.440
2020-06   99.710
2020-07   99.630
2020-08  100.190
2020-09  100.740
2020-10  100.180
2020-11  100.090
2020-12  100.330
2021-01  101.040
2021-02  101.580
2021-03  101.840
2021-04  101.980
2021-05  102.050
2021-06  102.050
2021-07  102.260
2021-08  102.750
2021-09  103.170
2021-10  103.350
2021-11  103.870
2021-12  104.040
2022-01  104.690
2022-02  105.300
2022-03  106.060
2022-04  106.850

### 시장금리 불러오기

In [170]:
interest_rates_df = pd.read_csv('./csv/시장금리.csv')
interest_rates_df.set_index('날짜', inplace=True)
interest_rates_df

,국고채_3년_평균,국고채_5년_평균,국고채_10년_평균,회사채_3년_평균,CD_91몰_평균,콜금리_1일몰_평균,기준금리
날짜,,,,,,,
2012-11,2.80,2.87,2.99,3.32,2.85,2.75,2.75
2012-12,2.85,2.98,3.13,3.30,2.88,2.75,2.75
2013-01,2.75,2.86,3.05,3.20,2.86,2.76,2.75
2013-02,2.70,2.83,3.04,3.06,2.83,2.75,2.75
2013-03,2.60,2.69,2.91,2.95,2.81,2.74,2.75
2013-04,2.55,2.63,2.84,2.91,2.80,2.75,2.75
2013-05,2.59,2.68,2.90,2.96,2.72,2.55,2.50
2013-06,2.87,3.08,3.31,3.24,2.69,2.49,2.50
2013-07,2.91,3.18,3.47,3.38,2.68,2.48,2.50
2013-08,2.94,3.26,3.61,3.33,2.66,2.50,2.50
2013-09,2.90,3.17,3.53,3.29,2.66,2.50,2.50
2013-10,2.83,3.08,3.44,3.25,2.66,2.50,2.50
2013-11,2.94,3.24,3.58,3.37,2.65,2.50,2.50
2013-12,2.94,3.30,3.65,3.36,2.65,2.50,2.50
2014-01,2.89,3.26,3.65,3.32,2.65,2.50,2.50
2014-02,2.85,3.16,3.52,3.28,2.65,2.49,2.50
2014-03,2.87,3.17,3.54,3.30,2.65,2.48,2.50
2014-04,2.88,3.17,3.54,3.30,2.65,2.49,2.50
2014-05,2.84,3.08,3.40,3.26,2.65,2.49,2.50
2014-06,2.75,2.97,3.30,3.17,2.65,2.48,2.50
2014-07,2.56,2.77,3.06,2.97,2.65,2.49,2.50
2014-08,2.54,2.77,3.09,2.93,2.52,2.34,2.25
2014-09,2.41,2.65,3.01,2.78,2.35,2.23,2.25
2014-10,2.24,2.42,2.77,2.60,2.21,2.06,2.00
2014-11,2.14,2.33,2.69,2.47,2.14,1.98,2.00
2014-12,2.14,2.33,2.68,2.46,2.13,1.99,2.00
2015-01,2.04,2.16,2.42,2.36,2.13,1.99,2.00
2015-02,2.02,2.11,2.35,2.30,2.12,1.99,2.00
2015-03,1.87,1.97,2.28,2.13,1.95,1.82,1.75
2015-04,1.74,1.86,2.18,1.99,1.81,1.73,1.75
2015-05,1.88,2.11,2.49,2.12,1.80,1.74,1.75
2015-06,1.77,2.04,2.47,2.01,1.70,1.57,1.50
2015-07,1.78,2.05,2.45,2.00,1.65,1.48,1.50
2015-08,1.74,1.95,2.31,1.98,1.64,1.49,1.50
2015-09,1.65,1.85,2.22,1.95,1.60,1.48,1.50
2015-10,1.63,1.78,2.09,1.96,1.58,1.48,1.50
2015-11,1.75,1.95,2.25,2.12,1.59,1.49,1.50
2015-12,1.72,1.90,2.18,2.14,1.67,1.48,1.50
2016-01,1.63,1.77,2.03,2.10,1.67,1.49,1.50
2016-02,1.47,1.59,1.83,1.95,1.64,1.49,1.50
2016-03,1.50,1.61,1.85,1.98,1.63,1.49,1.50
2016-04,1.47,1.57,1.81,1.94,1.61,1.49,1.50
2016-05,1.46,1.55,1.79,1.91,1.58,1.49,1.50
2016-06,1.33,1.41,1.62,1.79,1.43,1.29,1.25
2016-07,1.22,1.25,1.40,1.65,1.36,1.23,1.25
2016-08,1.24,1.26,1.42,1.65,1.35,1.23,1.25
2016-09,1.31,1.35,1.51,1.70,1.34,1.24,1.25
2016-10,1.36,1.41,1.60,1.78,1.35,1.23,1.25
2016-11,1.61,1.74,1.97,2.02,1.42,1.23,1.25
2016-12,1.69,1.87,2.16,2.16,1.54,1.23,1.25
2017-01,1.64,1.82,2.11,2.10,1.50,1.24,1.25
2017-02,1.67,1.86,2.16,2.13,1.49,1.23,1.25
2017-03,1.71,1.91,2.22,2.21,1.48,1.23,1.25
2017-04,1.68,1.86,2.18,2.20,1.43,1.23,1.25
2017-05,1.70,1.91,2.26,2.22,1.40,1.23,1.25
2017-06,1.67,1.86,2.17,2.21,1.38,1.24,1.25
2017-07,1.74,1.94,2.25,2.28,1.39,1.24,1.25
2017-08,1.78,1.99,2.29,2.32,1.39,1.23,1.25
2017-09,1.79,1.99,2.29,2.33,1.38,1.25,1.25
2017-10,2.03,2.25,2.46,2.57,1.38,1.24,1.25
2017-11,2.15,2.36,2.54,2.71,1.45,1.26,1.50
2017-12,2.10,2.30,2.47,2.65,1.66,1.51,1.50
2018-01,2.19,2.44,2.63,2.72,1.66,1.49,1.50
2018-02,2.28,2.54,2.77,2.82,1.65,1.49,1.50
2018-03,2.27,2.50,2.71,2.83,1.65,1.49,1.50
2018-04,2.19,2.44,2.66,2.79,1.65,1.47,1.50
2018-05,2.25,2.53,2.76,2.86,1.65,1.50,1.50
2018-06,2.18,2.44,2.66,2.81,1.65,1.49,1.50
2018-07,2.10,2.34,2.55,2.75,1.65,1.49,1.50
2018-08,2.02,2.24,2.46,2.66,1.65,1.50,1.50
2018-09,1.95,2.13,2.32,2.40,1.65,1.54,1.50
2018-10,2.01,2.16,2.34,2.45,1.68,1.52,1.50
2018-11,1.94,2.05,2.21,2.40,1.71,1.51,1.75
2018-12,1.83,1.89,1.99,2.30,1.91,1.77,1.75
2019-01,1.81,1.88,1.99,2.26,1.87,1.75,1.75
2019-02,1.80,1.87,1.99,2.25,1.87,1.76,1.75
2019-03,1.79,1.84,1.95,2.24,1.90,1.76,1.75
2019-04,1.74,1.77,1.89,2.21,1.89,1.75,1.75
2019-05,1.68,1.72,1.83,2.15,1.84,1.75,1.75
2019-06,1.50,1.53,1.62,2.00,1.80,1.76,1.75
2019-07,1.38,1.42,1.51,1.89,1.68,1.63,1.50
2019-08,1.16,1.20,1.25,1.69,1.49,1.51,1.50
2019-09,1.29,1.35,1.42,1.79,1.54,1.52,1.50
2019-10,1.36,1.44,1.58,1.86,1.46,1.35,1.25
2019-11,1.49,1.59,1.75,2.00,1.52,1.28,1.25
2019-12,1.39,1.48,1.65,1.95,1.53,1.28,1.25
2020-01,1.37,1.48,1.66,1.96,1.47,1.27,1.25
2020-02,1.25,1.36,1.54,1.85,1.42,1.24,1.25
2020-03,1.09,1.27,1.49,1.84,1.23,0.98,0.75
2020-04,1.02,1.26,1.50,2.15,1.10,0.74,0.75
2020-05,0.88,1.13,1.39,2.18,1.02,0.70,0.50
2020-06,0.85,1.13,1.39,2.22,0.79,0.48,0.50
2020-07,0.83,1.09,1.36,2.22,0.79,0.48,0.50
2020-08,0.83,1.09,1.37,2.19,0.68,0.50,0.50
2020-09,0.91,1.19,1.50,2.24,0.63,0.48,0.50
2020-10,0.91,1.20,1.51,2.24,0.63,0.51,0.50
2020-11,0.97,1.30,1.61,2.25,0.66,0.49,0.50
2020-12,0.97,1.32,1.68,2.21,0.66,0.51,0.50
2021-01,0.98,1.32,1.73,2.14,0.68,0.49,0.50
2021-02,1.00,1.35,1.85,2.06,0.73,0.49,0.50
2021-03,1.13,1.55,2.04,2.09,0.75,0.49,0.50
2021-04,1.14,1.58,2.04,1.98,0.74,0.48,0.50
2021-05,1.13,1.65,2.13,1.89,0.68,0.48,0.50
2021-06,1.30,1.70,2.10,1.91,0.66,0.51,0.50
2021-07,1.42,1.69,1.98,1.89,0.69,0.53,0.50
2021-08,1.41,1.65,1.91,1.84,0.77,0.56,0.75
2021-09,1.52,1.79,2.06,1.95,0.98,0.77,0.75
2021-10,1.84,2.15,2.40,2.30,1.08,0.74,0.75
2021-11,1.95,2.17,2.36,2.49,1.17,0.80,1.00
2021-12,1.80,1.98,2.19,2.41,1.27,1.01,1.00
2022-01,2.06,2.28,2.49,2.63,1.39,1.19,1.25
2022-02,2.29,2.50,2.69,2.87,1.50,1.22,1.25
2022-03,2.37,2.60,2.78,3.03,1.50,1.24,1.25
2022-04,2.94,3.14,3.22,3.63,1.64,1.30,1.50

### 소매판매지수 불러오기

In [171]:
socell_df = pd.read_csv('./csv/소매판매지수_1211_2204.csv')
socell_df = socell_df[['날짜','불변_총지수']]
socell_df.rename(columns={'불변_총지수' : '소매판매지수'}, inplace=True)
socell_df.set_index('날짜', inplace=True)
socell_df

         소매판매지수
날짜
2012-11    97.5
2012-12    99.8
2013-01    91.2
2013-02    86.8
2013-03    93.6
2013-04    91.9
2013-05    96.7
2013-06    93.2
2013-07    95.3
2013-08    91.1
2013-09    94.0
2013-10    97.1
2013-11    98.7
2013-12    99.9
2014-01    96.4
2014-02    86.7
2014-03    95.7
2014-04    92.5
2014-05    98.1
2014-06    94.5
2014-07    96.4
2014-08    94.0
2014-09    95.7
2014-10    97.4
2014-11   100.0
2014-12   105.2
2015-01    94.2
2015-02    92.9
2015-03    99.2
2015-04    98.7
2015-05   102.6
2015-06    95.0
2015-07    97.9
2015-08    95.6
2015-09   102.2
2015-10   106.3
2015-11   106.3
2015-12   109.0
2016-01    99.6
2016-02    95.6
2016-03   104.5
2016-04   102.1
2016-05   107.3
2016-06   103.4
2016-07   102.1
2016-08   100.8
2016-09   102.2
2016-10   108.4
2016-11   109.1
2016-12   111.2
2017-01   103.3
2017-02    95.2
2017-03   105.4
2017-04   103.9
2017-05   107.6
2017-06   104.2
2017-07   104.9
2017-08   101.3
2017-09   109.5
2017-10   108.0
2017-11   115.0
2017-12   112.9
2018-01   105.3
2018-02   101.7
2018-03   113.3
2018-04   109.9
2018-05   112.8
2018-06   108.7
2018-07   110.8
2018-08   107.0
2018-09   110.0
2018-10   113.6
2018-11   116.2
2018-12   116.4
2019-01   109.8
2019-02    99.8
2019-03   116.0
2019-04   111.4
2019-05   116.6
2019-06   110.0
2019-07   110.5
2019-08   111.5
2019-09   113.3
2019-10   115.7
2019-11   120.4
2019-12   121.6
2020-01   111.8
2020-02    97.8
2020-03   106.9
2020-04   108.9
2020-05   118.4
2020-06   116.9
2020-07   110.9
2020-08   111.7
2020-09   118.0
2020-10   115.8
2020-11   119.0
2020-12   119.1
2021-01   112.2
2021-02   106.2
2021-03   119.5
2021-04   118.9
2021-05   122.8
2021-06   119.5
2021-07   120.2
2021-08   116.5
2021-09   122.7
2021-10   125.0
2021-11   124.7
2021-12   127.2
2022-01   117.5
2022-02   107.9
2022-03   122.0
2022-04   119.4

### 카드 소비 합치기

In [172]:
total_csi = pd.merge(cpi_df, socell_df, how='left', left_index=True, right_index=True)
total_csi = pd.merge(total_csi, interest_rates_df,  how='left', left_index=True, right_index=True)
total_csi.drop_duplicates(inplace=True)
total_csi.head()

,소비자물가지수,소매판매지수,국고채_3년_평균,국고채_5년_평균,국고채_10년_평균,회사채_3년_평균,CD_91몰_평균,콜금리_1일몰_평균,기준금리
날짜,,,,,,,,,
2012-11,92.011,97.5,2.80,2.87,2.99,3.32,2.85,2.75,2.75
2012-12,92.175,99.8,2.85,2.98,3.13,3.30,2.88,2.75,2.75
2013-01,92.728,91.2,2.75,2.86,3.05,3.20,2.86,2.76,2.75
2013-02,93.038,86.8,2.70,2.83,3.04,3.06,2.83,2.75,2.75
2013-03,92.952,93.6,2.60,2.69,2.91,2.95,2.81,2.74,2.75

### 코로나 전 후 비교를 위한 기간설정

In [173]:
df_t = df_t.iloc[:86]
cpi_df = cpi_df.iloc[:-28]
interest_rates_df = interest_rates_df.iloc[:-28]
socell_df = socell_df.iloc[:-28]

### 상관관계

In [174]:
# 사용할 컬럼 불러오기
total_df = df_t
total_df = pd.DataFrame(total_df)
#total_df = total_df[total_df.columns.drop('일수')]
#total_df = total_df[total_df.columns.drop('합계')]
total_df = pd.merge(total_df,total_csi, how='left', left_index=True, right_index=True)
#total_df = pd.concat([total_df,total_csi],axis=1).reindex(total_csi.index)
total_df = total_df[['전자상거래/통신판매', '식료품','의류/잡화', '연료','가구/가전', '의료/보건', 
                     '자동차', '여행/교통', '스포츠/오락/여가', '서적/문구', '교육','숙박','음식점',
                     '공과금/개인및전문서비스', '금융/보험','소비자물가지수','소매판매지수','국고채_3년_평균',
                     '국고채_5년_평균','국고채_10년_평균','회사채_3년_평균','CD_91몰_평균','콜금리_1일몰_평균',
                     '기준금리']]
total_df.head()

,전자상거래/통신판매,식료품,의류/잡화,연료,가구/가전,의료/보건,자동차,여행/교통,스포츠/오락/여가,서적/문구,...,금융/보험,소비자물가지수,소매판매지수,국고채_3년_평균,국고채_5년_평균,국고채_10년_평균,회사채_3년_평균,CD_91몰_평균,콜금리_1일몰_평균,기준금리
날짜,,,,,,,,,,,,,,,,,,,,,
2012-11,29166.45,4778.33,14573.28,31259.23,9075.53,22958.88,19238.93,5963.69,10450.19,2692.31,...,10618.86,92.011,97.5,2.80,2.87,2.99,3.32,2.85,2.75,2.75
2012-12,29971.83,4895.34,14114.97,30662.26,7966.34,21824.52,22950.20,6390.76,9030.65,3010.90,...,10529.91,92.175,99.8,2.85,2.98,3.13,3.30,2.88,2.75,2.75
2013-01,28545.80,5024.76,11912.48,29951.78,7911.53,24766.40,15857.30,6774.19,8001.41,2802.50,...,10421.99,92.728,91.2,2.75,2.86,3.05,3.20,2.86,2.76,2.75
2013-02,24596.71,5510.28,11094.71,27288.38,7723.07,21469.13,16453.30,5812.63,6800.21,2502.28,...,9509.00,93.038,86.8,2.70,2.83,3.04,3.06,2.83,2.75,2.75
2013-03,26704.28,4775.35,13126.75,30351.01,9811.29,23354.47,20131.39,6079.25,9214.35,3681.25,...,10253.94,92.952,93.6,2.60,2.69,2.91,2.95,2.81,2.74,2.75

In [175]:
# 컬럼별 등락률 계산

col_list = []
col_list.append([col for col in total_df])

total_df1 = pd.DataFrame()

for i in col_list:
    total_df1[i] = total_df[i].pct_change()
    
total_df1 = total_df1.iloc[1:]
total_df1.head()

,전자상거래/통신판매,식료품,의류/잡화,연료,가구/가전,의료/보건,자동차,여행/교통,스포츠/오락/여가,서적/문구,...,금융/보험,소비자물가지수,소매판매지수,국고채_3년_평균,국고채_5년_평균,국고채_10년_평균,회사채_3년_평균,CD_91몰_평균,콜금리_1일몰_평균,기준금리
날짜,,,,,,,,,,,,,,,,,,,,,
2012-12,0.027613,0.024488,-0.031449,-0.019097,-0.122218,-0.049408,0.192904,0.071612,-0.135839,0.118333,...,-0.008377,0.001782,0.023590,0.017857,0.038328,0.046823,-0.006024,0.010526,0.000000,0.0
2013-01,-0.047579,0.026437,-0.156039,-0.023171,-0.006880,0.134797,-0.309056,0.059998,-0.113972,-0.069215,...,-0.010249,0.005999,-0.086172,-0.035088,-0.040268,-0.025559,-0.030303,-0.006944,0.003636,0.0
2013-02,-0.138342,0.096626,-0.068648,-0.088923,-0.023821,-0.133135,0.037585,-0.141945,-0.150124,-0.107126,...,-0.087602,0.003343,-0.048246,-0.018182,-0.010490,-0.003279,-0.043750,-0.010490,-0.003623,0.0
2013-03,0.085685,-0.133374,0.183154,0.112232,0.270387,0.087816,0.223547,0.045869,0.355010,0.471158,...,0.078341,-0.000924,0.078341,-0.037037,-0.049470,-0.042763,-0.035948,-0.007067,-0.003636,0.0
2013-04,0.045225,0.001931,-0.009763,-0.027114,-0.081842,-0.038601,0.004995,0.060437,0.028387,-0.204835,...,0.025264,-0.001388,-0.018162,-0.019231,-0.022305,-0.024055,-0.013559,-0.003559,0.003650,0.0

### 정규성 검정

In [176]:
from scipy import stats
from scipy.stats import shapiro

# 등락률 컬럼만 추출해서 pvalue 구하는 함수
def shap_pct(df_name):
    pct_colus = []
    pct_colus.append([col for col in df_name])
    for i in pct_colus:
        for j in i:
            shapiro_test = shapiro(df_name[j])
            print(j, "의 pvalue:", shapiro_test.pvalue)

In [177]:
shap_pct(total_df1)

전자상거래/통신판매 의 pvalue: 0.3099466860294342
식료품 의 pvalue: 0.18268708884716034
의류/잡화 의 pvalue: 0.002145733218640089
연료 의 pvalue: 0.5080863237380981
가구/가전 의 pvalue: 0.04512302577495575
의료/보건 의 pvalue: 0.33753088116645813
자동차 의 pvalue: 0.552711546421051
여행/교통 의 pvalue: 0.007531149312853813
스포츠/오락/여가 의 pvalue: 5.428668373497203e-06
서적/문구 의 pvalue: 3.1865913570072735e-06
교육 의 pvalue: 0.016805186867713928
숙박 의 pvalue: 0.26351138949394226
음식점 의 pvalue: 0.004374518990516663
공과금/개인및전문서비스 의 pvalue: 0.037681806832551956
금융/보험 의 pvalue: 0.003127526259049773
소비자물가지수 의 pvalue: 0.14466038346290588
소매판매지수 의 pvalue: 0.5582879185676575
국고채_3년_평균 의 pvalue: 0.031163373962044716
국고채_5년_평균 의 pvalue: 0.001721347332932055
국고채_10년_평균 의 pvalue: 0.008204905316233635
회사채_3년_평균 의 pvalue: 0.08730660378932953
CD_91몰_평균 의 pvalue: 8.520189709315673e-08
콜금리_1일몰_평균 의 pvalue: 3.0223399737766554e-12
기준금리 의 pvalue: 4.093405302219022e-16

In [178]:
total_df1 = total_df1.reset_index('날짜')
df_book = total_df1[['날짜','서적/문구','소비자물가지수','소매판매지수']]

In [179]:
month_df = df_book.copy()
month_df = month_df[['날짜','서적/문구']]
month_df.head()

        날짜     서적/문구
0  2012-12  0.118333
1  2013-01 -0.069215
2  2013-02 -0.107126
3  2013-03  0.471158
4  2013-04 -0.204835

In [180]:
month_df["날짜"] = month_df["날짜"].astype(str)
# 동월 전체 평균
month_df["서적/문구"][month_df["날짜"].str.endswith("12")].mean()

0.16692383500859187

In [181]:
pre_mean = month_df["서적/문구"].mean()

In [182]:
# 각 동월 전체 평균 리스트 저장

month_list = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
month_mean = []
for i in month_list:
    month_mean.append(month_df["서적/문구"][month_df["날짜"].str.endswith(i)].mean())
month_mean

[-0.09377506840603309,
 -0.08125907698439297,
 0.45989723679854866,
 -0.2637166991734027,
 -0.029655912467158898,
 -0.06021902317911471,
 0.13937164065191374,
 -0.060013373299463164,
 0.01768928819256829,
 -0.049443423235457855,
 0.01788438623691121,
 0.16692383500859187]

In [183]:
# "동월_평균_등락률" 컬럼 생성 및 값 저장

month_df["동월_평균_등락률"] = ""
for i in month_list:
        month_df["동월_평균_등락률"][month_df["날짜"].str.endswith(i)]  = month_df["서적/문구"][month_df["날짜"].str.endswith(i)].mean()
month_df.head(13)

C:\Users\82104\AppData\Local\Temp\ipykernel_22320\4237456934.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  month_df["동월_평균_등락률"][month_df["날짜"].str.endswith(i)]  = month_df["서적/문구"][month_df["날짜"].str.endswith(i)].mean()

         날짜     서적/문구 동월_평균_등락률
0   2012-12  0.118333  0.166924
1   2013-01 -0.069215 -0.093775
2   2013-02 -0.107126 -0.081259
3   2013-03  0.471158  0.459897
4   2013-04 -0.204835 -0.263717
5   2013-05 -0.104216 -0.029656
6   2013-06 -0.079599 -0.060219
7   2013-07  0.160407  0.139372
8   2013-08 -0.088365 -0.060013
9   2013-09  0.014355  0.017689
10  2013-10 -0.011677 -0.049443
11  2013-11  0.014116  0.017884
12  2013-12  0.168430  0.166924

In [184]:
# 동월별 양수 음수 등락률 평균값
import numpy as np

plus = [0.166924,0.459897,0.139372,0.017689,0.017884]
minus = [-0.093775,-0.081259,-0.263717,-0.029656,-0.060219,-0.060013,-0.049443]

# 평균 구하기
average_plus = np.mean(plus)
average_minus = np.mean(minus)

In [185]:
print(average_plus)
print(average_minus)

0.16035319999999997
-0.09115457142857143

In [186]:
# "전체_평균_대비" 컬럼 생성 및 값 저장

month_df["전체_평균_대비"] = ""

# 동월 평균 등락률이 전체 평균 보다 높거나 같으면 1, 낮으면 0
for i in range(0, 85):
    if month_df.loc[i, "동월_평균_등락률"] >= 0:
        if month_df.loc[i, "동월_평균_등락률"] >= average_plus:
            month_df.loc[i, "전체_평균_대비"] = 1
        else:
            month_df.loc[i, "전체_평균_대비"] = 0
    elif month_df.loc[i, "동월_평균_등락률"] < 0:
        if month_df.loc[i, "동월_평균_등락률"] >= average_minus:
            month_df.loc[i, "전체_평균_대비"] = 1
        else:
            month_df.loc[i, "전체_평균_대비"] = 0

month_df.tail()

         날짜     서적/문구 동월_평균_등락률 전체_평균_대비
80  2019-08 -0.016262 -0.060013        1
81  2019-09 -0.024028  0.017689        0
82  2019-10 -0.033313 -0.049443        1
83  2019-11  0.021241  0.017884        0
84  2019-12  0.121899  0.166924        1

In [187]:
df_book["동월_평균_등락률"] = month_df["동월_평균_등락률"]
df_book["전체_평균_대비"] = month_df["전체_평균_대비"]

C:\Users\82104\AppData\Local\Temp\ipykernel_22320\1541011350.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_book["동월_평균_등락률"] = month_df["동월_평균_등락률"]
C:\Users\82104\AppData\Local\Temp\ipykernel_22320\1541011350.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_book["전체_평균_대비"] = month_df["전체_평균_대비"]

In [188]:
df_book

         날짜     서적/문구   소비자물가지수    소매판매지수 동월_평균_등락률 전체_평균_대비
0   2012-12  0.118333  0.001782  0.023590  0.166924        1
1   2013-01 -0.069215  0.005999 -0.086172 -0.093775        0
2   2013-02 -0.107126  0.003343 -0.048246 -0.081259        1
3   2013-03  0.471158 -0.000924  0.078341  0.459897        1
4   2013-04 -0.204835 -0.001388 -0.018162 -0.263717        0
5   2013-05 -0.104216  0.000000  0.052231 -0.029656        1
6   2013-06 -0.079599 -0.001217 -0.036194 -0.060219        1
7   2013-07  0.160407  0.002146  0.022532  0.139372        0
8   2013-08 -0.088365  0.003541 -0.044071 -0.060013        1
9   2013-09  0.014355  0.001941  0.031833  0.017689        0
10  2013-10 -0.011677 -0.003051  0.032979 -0.049443        1
11  2013-11  0.014116 -0.000193  0.016478  0.017884        0
12  2013-12  0.168430  0.001214  0.012158  0.166924        1
13  2014-01 -0.103812  0.005374 -0.035035 -0.093775        0
14  2014-02 -0.081359  0.002667 -0.100622 -0.081259        1
15  2014-03  0.459274  0.001841  0.103806  0.459897        1
16  2014-04 -0.286140  0.000648 -0.033438 -0.263717        0
17  2014-05 -0.021034  0.001645  0.060541 -0.029656        1
18  2014-06 -0.091243 -0.001282 -0.036697 -0.060219        1
19  2014-07  0.192122  0.001464  0.020106  0.139372        0
20  2014-08 -0.068261  0.001748 -0.024896 -0.060013        1
21  2014-09  0.020185 -0.000645  0.018085  0.017689        0
22  2014-10 -0.035319 -0.003016  0.017764 -0.049443        1
23  2014-11  0.036877 -0.002017  0.026694  0.017884        0
24  2014-12  0.142098 -0.000096  0.052000  0.166924        1
25  2015-01 -0.075154  0.006776 -0.104563 -0.093775        0
26  2015-02 -0.116567 -0.000592 -0.013800 -0.081259        1
27  2015-03  0.514840  0.000095  0.067815  0.459897        1
28  2015-04 -0.262698  0.000307 -0.005040 -0.263717        0
29  2015-05 -0.046091  0.002801  0.039514 -0.029656        1
30  2015-06 -0.090228  0.000200 -0.074074 -0.060219        1
31  2015-07  0.190268  0.001802  0.030526  0.139372        0
32  2015-08 -0.080040  0.001399 -0.023493 -0.060013        1
33  2015-09  0.016307 -0.002594  0.069038  0.017689        0
34  2015-10 -0.021849  0.000000  0.040117 -0.049443        1
35  2015-11 -0.061074 -0.001895  0.000000  0.017884        0
36  2015-12  0.281181  0.002996  0.025400  0.166924        1
37  2016-01 -0.111393  0.001704 -0.086239 -0.093775        0
38  2016-02 -0.075779  0.004284 -0.040161 -0.081259        1
39  2016-03  0.455817 -0.002583  0.093096  0.459897        1
40  2016-04 -0.284409  0.001887 -0.022967 -0.263717        0
41  2016-05 -0.030636  0.000596  0.050930 -0.029656        1
42  2016-06 -0.033689 -0.000199 -0.036347 -0.060219        1
43  2016-07  0.145196 -0.001883 -0.012573  0.139372        0
44  2016-08 -0.085173  0.002578 -0.012733 -0.060013        1
45  2016-09  0.009137  0.005958  0.013889  0.017689        0
46  2016-10 -0.023686  0.001371  0.060665 -0.049443        1
47  2016-11  0.019742 -0.001473  0.006458  0.017884        0
48  2016-12  0.164018  0.001091  0.019248  0.166924        1
49  2017-01 -0.140694  0.010629 -0.071043 -0.093775        0
50  2017-02 -0.005742  0.002732 -0.078412 -0.081259        1
51  2017-03  0.411053 -0.000686  0.107143  0.459897        1
52  2017-04 -0.264739 -0.001261 -0.014231 -0.263717        0
53  2017-05 -0.035323  0.001067  0.035611 -0.029656        1
54  2017-06 -0.030183 -0.002132 -0.031599 -0.060219        1
55  2017-07  0.109307  0.001654  0.006718  0.139372        0
56  2017-08 -0.050647  0.005733 -0.034318 -0.060013        1
57  2017-09  0.077957  0.001163  0.080948  0.017689        0
58  2017-10 -0.167283 -0.000968 -0.013699 -0.049443        1
59  2017-11  0.075560 -0.007443  0.064815  0.017884        0
60  2017-12  0.179838  0.003606 -0.018261  0.166924        1
61  2018-01 -0.114661  0.004176 -0.067316 -0.093775        0
62  2018-02 -0.075422  0.007635 -0.034188 -0.081259        1
63  2018-03  0.477393 -0.001052  0.114061  0.459897        1
64  2018-04 -0.277346  0.001823 -0.030009 -0.263717        0
65  2018-05  0.023894  0.000485  0.026388 -0.029656        1
66  2018-06 -0.052572 -0.002021 -0.036348 -0.060219        1
67  2018-07  0.100549 -0.001913  0.019319  0.139372        0
68  2018-08 -0.031346  0.008845 -0.034296 -0.060013        1
69  2018-09  0.009911  0.007631  0.028037  0.017689        0
70  2018-10 -0.052978 -0.001796  0.032727 -0.049443        1
71  2018-11  0.018729 -0.007107  0.022887  0.017884        0
72  2018-12  0.159593 -0.003443  0.001721  0.166924        1
73  2019-01 -0.041497 -0.001051 -0.056701 -0.093775        0
74  2019-02 -0.106819  0.004318 -0.091075 -0.081259        1
75  2019-03  0.429745 -0.001913  0.162325  0.459897        1
76  2019-04 -0.265850  0.003632 -0.039655 -0.263717        0
77  2019-05  0.005815  0.001719  0.046679 -0.029656        1
78  2019-06 -0.044019 -0.001616 -0.056604 -0.060219        1
79  2019-07  0.077752 -0.003056  0.004545  0.139372        0
80  2019-08 -0.016262  0.002400  0.009050 -0.060013        1
81  2019-09 -0.024028  0.003711  0.016143  0.017689        0
82  2019-10 -0.033313  0.002475  0.021183 -0.049443        1
83  2019-11  0.021241 -0.005598  0.040622  0.017884        0
84  2019-12  0.121899  0.002392  0.009967  0.166924        1

In [189]:
pd.options.display.max_rows = None

In [190]:
df_book.describe()

           서적/문구    소비자물가지수     소매판매지수
count  85.000000  85.000000  85.000000
mean    0.015444   0.000952   0.003923
std     0.175948   0.003223   0.051923
min    -0.286140  -0.007443  -0.104563
25%    -0.080040  -0.001261  -0.034296
50%    -0.024028   0.001091   0.009050
75%     0.077957   0.002578   0.032727
max     0.514840   0.010629   0.162325

In [191]:
import numpy as np

df_book["날짜"] = df_book["날짜"].astype(str)
df_book["소비"] = ""

for i in range(0, 13):
    for j in range(12, 85):
        if df_book.loc[i, "날짜"].endswith("03"):
            df_book.loc[i, "소비"] = 1
        else:
            if df_book.loc[i,"서적/문구"] > 0: 
                if df_book.loc[i,"소매판매지수"] >= df_book["소매판매지수"].quantile(q=0.5):
                    df_book.loc[i,"소비"] = 1
                elif df_book.loc[i,"소매판매지수"] >= df_book["소매판매지수"].quantile(q=0.25):
                    if df_book.loc[i,"소비자물가지수"] <= df_book["소비자물가지수"].quantile(q=0.75):
                        df_book.loc[i,"소비"] = 1
                    else:
                        df_book.loc[i,"소비"] = 0
                elif df_book.loc[i,"소매판매지수"] < df_book["소매판매지수"].quantile(q=0.25):
                    df_book.loc[i,"소비"] = 0

            elif df_book.loc[i, "서적/문구"] <= 0:
                if df_book.loc[i,"소매판매지수"] <= df_book["소매판매지수"].quantile(q=0.75):
                    df_book.loc[i,"소비"] = 0
                elif df_book.loc[i,"소매판매지수"] > df_book["소매판매지수"].quantile(q=0.75):
                    if df_book.loc[i,"소비자물가지수"] > df_book["소비자물가지수"].quantile(q=0.5):
                        df_book.loc[i,"소비"] = 0
                    else:
                        df_book.loc[i,"소비"] = 1
                    
                    
        if df_book["서적/문구"].loc[j] > 0:
            if df_book['서적/문구'].loc[j-12] > 0:
                if df_book["전체_평균_대비"].loc[j] == 1:
                    df_book.loc[j,"소비"] = 1
                elif df_book["전체_평균_대비"].loc[j] != 1:
                    if df_book.loc[j,'소매판매지수'] >= 0.009050:
                        if df_book.loc[j,'소비자물가지수'] > 0.001091:
                            df_book.loc[j,"소비"] = 0
                        else:
                            df_book.loc[j,"소비"] = 1
                    elif df_book.loc[j,'소매판매지수'] < 0.009050:
                        df_book.loc[j,"소비"] = 0
                        
            elif df_book['서적/문구'].loc[j-12] <= 0:
                if df_book["전체_평균_대비"].loc[j] == 1:
                    df_book.loc[j,'소비'] = 1
                elif df_book["전체_평균_대비"].loc[j] != 1:
                    if df_book.loc[j,'소매판매지수'] >= 0.009050:
                        if df_book.loc[j,'소비자물가지수'] > 0.001091:
                            df_book.loc[j,'소비'] = 0
                        else:
                            df_book.loc[j,'소비'] = 1
                    else:
                        df_book.loc[j,'소비'] = 0
                    
        elif df_book["서적/문구"].loc[j] <= 0:
            if df_book['서적/문구'].loc[j-12] <= 0:
                if df_book["전체_평균_대비"].loc[j] == 0:
                    df_book.loc[j,"소비"] =0
                elif df_book["전체_평균_대비"].loc[j] != 0:
                    if df_book.loc[j,'소매판매지수'] >= 0.009050:
                        if df_book.loc[j,'소비자물가지수'] > 0.001091:
                            df_book.loc[j,'소비'] = 0
                        else:
                            df_book.loc[j,'소비'] = 1
                    else:
                        df_book.loc[j,'소비'] = 0
                        
            elif df_book['서적/문구'].loc[j-12] >= 0:
                if df_book.loc[j,'전체_평균_대비'] == 0:
                    df_book.loc[j,'소비'] = 0
                elif df_book.loc[j,'전체_평균_대비'] != 0:
                    if df_book.loc[j,'소매판매지수'] >= 0.009050:
                        if df_book.loc[j,'소비자물가지수'] > 0.001091:
                            df_book.loc[j,'소비'] = 0
                        else:
                            df_book.loc[j,'소비'] = 1
                    else:
                        df_book.loc[j,'소비'] = 0
                        
df_book

C:\Users\82104\AppData\Local\Temp\ipykernel_22320\2273680911.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_book["날짜"] = df_book["날짜"].astype(str)
C:\Users\82104\AppData\Local\Temp\ipykernel_22320\2273680911.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_book["소비"] = ""

         날짜     서적/문구   소비자물가지수    소매판매지수 동월_평균_등락률 전체_평균_대비 소비
0   2012-12  0.118333  0.001782  0.023590  0.166924        1  1
1   2013-01 -0.069215  0.005999 -0.086172 -0.093775        0  0
2   2013-02 -0.107126  0.003343 -0.048246 -0.081259        1  0
3   2013-03  0.471158 -0.000924  0.078341  0.459897        1  1
4   2013-04 -0.204835 -0.001388 -0.018162 -0.263717        0  0
5   2013-05 -0.104216  0.000000  0.052231 -0.029656        1  1
6   2013-06 -0.079599 -0.001217 -0.036194 -0.060219        1  0
7   2013-07  0.160407  0.002146  0.022532  0.139372        0  1
8   2013-08 -0.088365  0.003541 -0.044071 -0.060013        1  0
9   2013-09  0.014355  0.001941  0.031833  0.017689        0  1
10  2013-10 -0.011677 -0.003051  0.032979 -0.049443        1  1
11  2013-11  0.014116 -0.000193  0.016478  0.017884        0  1
12  2013-12  0.168430  0.001214  0.012158  0.166924        1  1
13  2014-01 -0.103812  0.005374 -0.035035 -0.093775        0  0
14  2014-02 -0.081359  0.002667 -0.100622 -0.081259        1  0
15  2014-03  0.459274  0.001841  0.103806  0.459897        1  1
16  2014-04 -0.286140  0.000648 -0.033438 -0.263717        0  0
17  2014-05 -0.021034  0.001645  0.060541 -0.029656        1  0
18  2014-06 -0.091243 -0.001282 -0.036697 -0.060219        1  0
19  2014-07  0.192122  0.001464  0.020106  0.139372        0  0
20  2014-08 -0.068261  0.001748 -0.024896 -0.060013        1  0
21  2014-09  0.020185 -0.000645  0.018085  0.017689        0  1
22  2014-10 -0.035319 -0.003016  0.017764 -0.049443        1  1
23  2014-11  0.036877 -0.002017  0.026694  0.017884        0  1
24  2014-12  0.142098 -0.000096  0.052000  0.166924        1  1
25  2015-01 -0.075154  0.006776 -0.104563 -0.093775        0  0
26  2015-02 -0.116567 -0.000592 -0.013800 -0.081259        1  0
27  2015-03  0.514840  0.000095  0.067815  0.459897        1  1
28  2015-04 -0.262698  0.000307 -0.005040 -0.263717        0  0
29  2015-05 -0.046091  0.002801  0.039514 -0.029656        1  0
30  2015-06 -0.090228  0.000200 -0.074074 -0.060219        1  0
31  2015-07  0.190268  0.001802  0.030526  0.139372        0  0
32  2015-08 -0.080040  0.001399 -0.023493 -0.060013        1  0
33  2015-09  0.016307 -0.002594  0.069038  0.017689        0  1
34  2015-10 -0.021849  0.000000  0.040117 -0.049443        1  1
35  2015-11 -0.061074 -0.001895  0.000000  0.017884        0  0
36  2015-12  0.281181  0.002996  0.025400  0.166924        1  1
37  2016-01 -0.111393  0.001704 -0.086239 -0.093775        0  0
38  2016-02 -0.075779  0.004284 -0.040161 -0.081259        1  0
39  2016-03  0.455817 -0.002583  0.093096  0.459897        1  1
40  2016-04 -0.284409  0.001887 -0.022967 -0.263717        0  0
41  2016-05 -0.030636  0.000596  0.050930 -0.029656        1  1
42  2016-06 -0.033689 -0.000199 -0.036347 -0.060219        1  0
43  2016-07  0.145196 -0.001883 -0.012573  0.139372        0  0
44  2016-08 -0.085173  0.002578 -0.012733 -0.060013        1  0
45  2016-09  0.009137  0.005958  0.013889  0.017689        0  0
46  2016-10 -0.023686  0.001371  0.060665 -0.049443        1  0
47  2016-11  0.019742 -0.001473  0.006458  0.017884        0  0
48  2016-12  0.164018  0.001091  0.019248  0.166924        1  1
49  2017-01 -0.140694  0.010629 -0.071043 -0.093775        0  0
50  2017-02 -0.005742  0.002732 -0.078412 -0.081259        1  0
51  2017-03  0.411053 -0.000686  0.107143  0.459897        1  1
52  2017-04 -0.264739 -0.001261 -0.014231 -0.263717        0  0
53  2017-05 -0.035323  0.001067  0.035611 -0.029656        1  1
54  2017-06 -0.030183 -0.002132 -0.031599 -0.060219        1  0
55  2017-07  0.109307  0.001654  0.006718  0.139372        0  0
56  2017-08 -0.050647  0.005733 -0.034318 -0.060013        1  0
57  2017-09  0.077957  0.001163  0.080948  0.017689        0  0
58  2017-10 -0.167283 -0.000968 -0.013699 -0.049443        1  0
59  2017-11  0.075560 -0.007443  0.064815  0.017884        0  1
60  2017-12  0.179838  0.003606 -0.018261  0.166924        1  1
61  2018-01 -0.114661  0.004176 -0.067316 -0.093775        0  0
62  2018-02 -0.075422  0.007635 -0.034188 -0.081259        1  0
63  2018-03  0.477393 -0.001052  0.114061  0.459897        1  1
64  2018-04 -0.277346  0.001823 -0.030009 -0.263717        0  0
65  2018-05  0.023894  0.000485  0.026388 -0.029656        1  1
66  2018-06 -0.052572 -0.002021 -0.036348 -0.060219        1  0
67  2018-07  0.100549 -0.001913  0.019319  0.139372        0  1
68  2018-08 -0.031346  0.008845 -0.034296 -0.060013        1  0
69  2018-09  0.009911  0.007631  0.028037  0.017689        0  0
70  2018-10 -0.052978 -0.001796  0.032727 -0.049443        1  1
71  2018-11  0.018729 -0.007107  0.022887  0.017884        0  1
72  2018-12  0.159593 -0.003443  0.001721  0.166924        1  1
73  2019-01 -0.041497 -0.001051 -0.056701 -0.093775        0  0
74  2019-02 -0.106819  0.004318 -0.091075 -0.081259        1  0
75  2019-03  0.429745 -0.001913  0.162325  0.459897        1  1
76  2019-04 -0.265850  0.003632 -0.039655 -0.263717        0  0
77  2019-05  0.005815  0.001719  0.046679 -0.029656        1  1
78  2019-06 -0.044019 -0.001616 -0.056604 -0.060219        1  0
79  2019-07  0.077752 -0.003056  0.004545  0.139372        0  0
80  2019-08 -0.016262  0.002400  0.009050 -0.060013        1  0
81  2019-09 -0.024028  0.003711  0.016143  0.017689        0  0
82  2019-10 -0.033313  0.002475  0.021183 -0.049443        1  0
83  2019-11  0.021241 -0.005598  0.040622  0.017884        0  1
84  2019-12  0.121899  0.002392  0.009967  0.166924        1  1

In [192]:
df_book[df_book["소비"]==1]

         날짜     서적/문구   소비자물가지수    소매판매지수 동월_평균_등락률 전체_평균_대비 소비
0   2012-12  0.118333  0.001782  0.023590  0.166924        1  1
3   2013-03  0.471158 -0.000924  0.078341  0.459897        1  1
5   2013-05 -0.104216  0.000000  0.052231 -0.029656        1  1
7   2013-07  0.160407  0.002146  0.022532  0.139372        0  1
9   2013-09  0.014355  0.001941  0.031833  0.017689        0  1
10  2013-10 -0.011677 -0.003051  0.032979 -0.049443        1  1
11  2013-11  0.014116 -0.000193  0.016478  0.017884        0  1
12  2013-12  0.168430  0.001214  0.012158  0.166924        1  1
15  2014-03  0.459274  0.001841  0.103806  0.459897        1  1
21  2014-09  0.020185 -0.000645  0.018085  0.017689        0  1
22  2014-10 -0.035319 -0.003016  0.017764 -0.049443        1  1
23  2014-11  0.036877 -0.002017  0.026694  0.017884        0  1
24  2014-12  0.142098 -0.000096  0.052000  0.166924        1  1
27  2015-03  0.514840  0.000095  0.067815  0.459897        1  1
33  2015-09  0.016307 -0.002594  0.069038  0.017689        0  1
34  2015-10 -0.021849  0.000000  0.040117 -0.049443        1  1
36  2015-12  0.281181  0.002996  0.025400  0.166924        1  1
39  2016-03  0.455817 -0.002583  0.093096  0.459897        1  1
41  2016-05 -0.030636  0.000596  0.050930 -0.029656        1  1
48  2016-12  0.164018  0.001091  0.019248  0.166924        1  1
51  2017-03  0.411053 -0.000686  0.107143  0.459897        1  1
53  2017-05 -0.035323  0.001067  0.035611 -0.029656        1  1
59  2017-11  0.075560 -0.007443  0.064815  0.017884        0  1
60  2017-12  0.179838  0.003606 -0.018261  0.166924        1  1
63  2018-03  0.477393 -0.001052  0.114061  0.459897        1  1
65  2018-05  0.023894  0.000485  0.026388 -0.029656        1  1
67  2018-07  0.100549 -0.001913  0.019319  0.139372        0  1
70  2018-10 -0.052978 -0.001796  0.032727 -0.049443        1  1
71  2018-11  0.018729 -0.007107  0.022887  0.017884        0  1
72  2018-12  0.159593 -0.003443  0.001721  0.166924        1  1
75  2019-03  0.429745 -0.001913  0.162325  0.459897        1  1
77  2019-05  0.005815  0.001719  0.046679 -0.029656        1  1
83  2019-11  0.021241 -0.005598  0.040622  0.017884        0  1
84  2019-12  0.121899  0.002392  0.009967  0.166924        1  1

In [193]:
df_book.to_csv('rw.csv',encoding='utf-8')